### ISSUE TITLE
how do i train on specific domain corpus data?

### ISSUE THREAD

**Issue by sjrnf-j** [pytorch/torchtune#1008]
I want to full-finetune llama3 model, not Llama3-Instruct model, using corpus data.
I only found fine-tuning on the chat data.

Is there any instructions about this issue?

**Comment by joecummings** [comment]
Hi @sjrnf-j - thanks for checking out torchtune! If I understand correctly, there's two things to your question:

1) You want to use the base llama3 model, not the instruction tuned model.
2) You want to do some continuous pre-training, not in a chat format.

WRT point 1, you can actually download and load whichever Llama3 model you'd like. Simply switch out `tune download meta-llama/Llama-3-8B-Instruct ...` with `tune download meta-llama/Llama-3-8B ...` and then point to the local directory holding your newly downloaded base model. 

> For a little extra context here, the majority of our users want to do some kind of instruction/chat interaction with their model, in which case the Llama3 Instruct model is significantly better.

WRT the second point, we don't currently support this type of data training OOTB; however, @RdoubleA is super close to landing that PR! You can follow along here: #868

**Comment by sjrnf-j** [comment]
thanks a lot

**Comment by RdoubleA** [comment]
This should be supported now with `TextCompletionDataset`, take a look at how to do this here: https://pytorch.org/torchtune/main/tutorials/datasets.html#custom-unstructured-text-corpus

Closing this issue but please reopen if you're still having difficulties getting this set up!
