### ISSUE TITLE
HF Checkpointer doesn't support loading quantized models

### ISSUE THREAD

**Issue by SalmanMohammadi** [pytorch/torchtune#1009]
Trying 
```
  quantizer: 
    _component_: torchtune.utils.quantization.Int8WeightOnlyQuantizer
```
In a config for a `generate` recipe using HF checkpoints gives 
```
TypeError: load_checkpoint() got an unexpected keyword argument 'weights_only'
```
Since loading quantized models [isn't implemented](https://github.com/pytorch/torchtune/blob/29ae975fc6d2f8e85ce33634116e0bda0472253c/torchtune/utils/_checkpointing/_checkpointer.py#L344) in `FullModelHFCheckpointer.load_checkpoint()`

Is this mainly because we're having to load multiple checkpoints from HF?

**Comment by kartikayk** [comment]
Thanks for opening this issue!

The reason for this is that we currently don't support converting the quantized model into HF Format and this is always stored in tune format. @jerryzh168 can provide more insights into the technical reasons behind this, but my understanding is that we potentially have additional artifacts as part of the quantized model checkpoint and its not always clear what conversion means in this context.

**Comment by SalmanMohammadi** [comment]
Thanks so much for the explanation :) happy to close this for now.
