### ISSUE TITLE
Clarify in using local dataset

### ISSUE THREAD

**Issue by alirezag** [pytorch/torchtune#1021]
The tutorial [here](https://github.com/pytorch/torchtune/blob/main/docs/source/tutorials/datasets.rst) suggest we can set source to 'txt' and use 'data_files' key to load local files. But after I get an error saying the dataset does not exist on hugging face. Still fater creaing a dummy HF dataset it still doesn't work.

Using the component  directly in code works: 

```python
# Load in tokenizer
tokenizer = ...
dataset = text_completion_dataset(
    tokenizer,
    source="txt",
    data_files="path/to/my_data.txt",
)

**Comment by RdoubleA** [comment]
Hi @alirezag, can you share the exact error you are getting? And is this from specifying a local dataset in the config or in code?
