### ISSUE TITLE
codellama-2 finetuning fails

### ISSUE THREAD

**Issue by Kushalamummigatti** [pytorch/torchtune#1034]
Am using the same config file given in the recipe to finetune the CodeLlama-2 model. But am getting a strange error attached in the below SS. 
![gitissueimage](https://github.com/pytorch/torchtune/assets/62338340/0e5b208d-87b7-4cbe-9200-832e8658fbd5)

**Comment by SalmanMohammadi** [comment]
Hey @Kushalamummigatti, thanks for raising this. The screenshot is just showing as a blank white image for me, could you try re-upload?

**Comment by Kushalamummigatti** [comment]
@SalmanMohammadi updated with new one.

**Comment by SalmanMohammadi** [comment]
Can you make sure you installed the nightly version? See [here](https://pytorch.org/torchtune/main/install.html#install-nightly-build). I've included the command for ease:
```
pip install --pre torchtune --extra-index-url https://download.pytorch.org/whl/nightly/cpu --no-cache-dir
```

**Comment by Kushalamummigatti** [comment]
@SalmanMohammadi No am facing new error now. 
<img width="650" alt="image" src="https://github.com/pytorch/torchtune/assets/62338340/3537cba8-afc6-4eed-b1b9-5ce228785f17">

**Comment by SalmanMohammadi** [comment]
Could you please confirm the version of PyTorch you have installed?

**Comment by ebsmothers** [comment]
@Kushalamummigatti do you still need help with this? I am going to close it since it's been stale for a bit, but if you do still need help please reopen and I will gladly take a look.
