### ISSUE TITLE
FP16

### ISSUE THREAD

**Issue by eghouti** [pytorch/torchtune#1039]
Hello. I have a pre-trained (on Magatron-lm) model that uses fp16 format. I want to convert it and fine tune it on torchtune, but I found that torchtune does not support fp16 format. Is there an alternative or a solution for that? thank you for your help

**Comment by ebsmothers** [comment]
Hi @eghouti thanks for creating the issue. I caught up a bit with the discussion on Discord. I believe a lot of models are saved in fp16, which we then load into bf16 with no problems. E.g. I think even the Llama2 weights on Hugging Face are in fp16:

```
$ tune download meta-llama/Llama-2-7b-hf --output-dir /tmp/Llama-2-7b-hf --hf-token <HF_TOKEN>
$ python3
>>> import torch
>>> sd = torch.load('/tmp/Llama-2-7b-hf/pytorch_model-00002-of-00002.bin')
>>> sd['model.layers.24.self_attn.q_proj.weight'].dtype
torch.float16
```

However, we then load this checkpoint into torchtune and fine-tune in bf16, which tends to be more stable for training. So unless there's a specific reason you need to load in fp16 (e.g. your weights are all really close to 0), I think bf16 is fine (even preferable) for fine-tuning. Let me know if this makes sense or if there's other info I'm missing here, thanks!
