### ISSUE TITLE
Flush logs to disk as soon as possible

### ISSUE THREAD

**Issue by nguyentanthong** [pytorch/torchtune#1040]
https://github.com/pytorch/torchtune/blob/0c4056a6a55bfffd3cec7a99a13dc978cfe85963/torchtune/utils/metric_logging.py#L98-L105

Current implementation does not flush the log to disk right away. It is better if we add 
```
self._file.flush()
```
at the end of these logging methods.

**Comment by ebsmothers** [comment]
Resolved by #1078
