### ISSUE TITLE
Refactor InstructTemplate and ChatFormat

### ISSUE THREAD

**Issue by RdoubleA** [pytorch/torchtune#1044]
Prompt templates have been trending towards being handled as special tokens in the tokenizer (llama2 -> llama3, mistral v2 -> mistral v3), making the classes `InstructTemplate` and `ChatFormat` less practical. Instruct data can also be considered a form of single-turn chat data, and more models are leaning into the chat / conversation format especially with adding tool-calling capabilities.

- Investigate and determine if `InstructTemplate` is still useful for quick mapping of data table columns to a prompt and should remain a standalone class
- Consider merging `InstructTemplate` and `ChatFormat` into one `PromptTemplate` class to support legacy templating behavior
- Figure out plan for customizing special tokens in a tokenizer for any arbitrary template a user may want to fine-tune with

See discussion in #1019 for more context. cc @ebsmothers

**Comment by joecummings** [comment]
@RdoubleA  Can this be closed?
