### ISSUE TITLE
[Bug] Phi3 tokenizer adds a extra start token when `ignore_system_prompts=True`

### ISSUE THREAD

**Issue by hmosousa** [pytorch/torchtune#1063]
Hi there,

When running the `phi3_mini_tokenizer` I noticed that if the messages have a `"system"` message and the tokenizer parameter `ignore_system_prompts` is set to `True` the tokenizer produces an extra start of turn token. Code to replicate the bug:

```python
from torchtune.data import Message
from torchtune.models.phi3 import phi3_mini_tokenizer

messages = [
    Message(role="system", content="system content"),
    Message(role="user", content="users content")
]
tokenizer = phi3_mini_tokenizer("path/to/tokenizer.model")
input_ids, _ = tokenizer.tokenize_messages(messages, ignore_system_prompts=True)
print(input_ids)  # [1, 1, 32010, 29871, 13, 7193, 2793, 32007, 29871, 13]
```

One way to fix this would be to add the condition `if message.role == "system" and ignore_system_prompts: continue` at the beginning of the message loop:

https://github.com/pytorch/torchtune/blob/8f93a1c748d255f2b932e02f7de14a7f4522e64e/torchtune/models/phi3/_sentencepiece.py#L173

Should I create a PR with that solution?

**Comment by joecummings** [comment]
Great catch! We'd love to accept a PR with this change.
