### ISSUE TITLE
HFCheckpointer saves to .pt instead of .safetensors

### ISSUE THREAD

**Issue by dcsuka** [pytorch/torchtune#1068]
Is it possible to checkpoint a full parameter fine-tuning of Llama3 8B with 4 separate sharded .safetensors checkpoint files per epoch as output instead of 4 separate sharded .pt files? That would make it easier to infer from finetuned models using the Huggingface transformers API, because we could just replace the original .safetensors files with our finetuned .safetensors files. Or is it very easy to convert .pt to .safetensors after torchtune automatically saves them as .pt? Here is the checkpointer section of my config:

```
checkpointer:
  _component_: torchtune.utils.FullModelHFCheckpointer
  checkpoint_dir: tmp/meta-llama/Meta-Llama-3-8B-Instruct/
  checkpoint_files: [
    model-00001-of-00004.safetensors,
    model-00002-of-00004.safetensors,
    model-00003-of-00004.safetensors,
    model-00004-of-00004.safetensors,
  ]
  recipe_checkpoint: null
  output_dir: tmp/meta-llama/output/
  model_type: LLAMA3
resume_from_checkpoint: False
```

**Comment by mahdilashkari** [comment]
@dcsuka How do you convert the output ( .pt) files to .safetensors currently? I also have this problem.

**Comment by SalmanMohammadi** [comment]
Hey @dcsuka and @mahdilashkari. Thanks for raising! Does the answer in [this issue](https://github.com/pytorch/torchtune/issues/878) help?

**Comment by mahdilashkari** [comment]
Hi, thanks dear Salman, Yes it solved my problems.

**Comment by ebsmothers** [comment]
Thanks @SalmanMohammadi for sorting this out! Gonna close this issue since it seems to be resolved, but feel free to reopen if anything else comes up here.
