### ISSUE TITLE
Investigate possible memory leak with sample packing

### ISSUE THREAD

**Issue by joecummings** [pytorch/torchtune#1097]
Following the gist below, a dataset of size ~3 GB with 2M entries takes up more than 900 GB of CPU memory while doing offline sample packing. 

https://gist.github.com/joecummings/642eaa9ce539ad93360ee3f999dbcfa3

Need to get to the bottom of this.

**Comment by joecummings** [comment]
Based on my understanding, the ~handwavy peak memory allocated for sample packing (using 3GB dataset as example) should be:

```
3gb (entire original dataset loaded into memory)+
3gb (entire dataset now as packs w/ labels) +
3gb (input_pos for packs) +
3gb * 9gb (seq x seq mask for every pack)
-------------------------------------------
36gb
```

**Comment by joecummings** [comment]
To process 50k samples (~ 2.2% of the entire dataset) consumes 41gb of memory.

To process 100k samples (~ 4.3% of the entire dataset) consumes 81 gb of memory. 

This seems like the memory is scaling linearly, based on this looks like the entire process would consume ~1886 gb of memory.

**Comment by joecummings** [comment]
Using the following code, I'm calculating the size of the packs directly:

```
packs = [
	{"tensor": ... , "mask": ... , "labels": ... , "input_pos": ... },
	{"tensor": ... , "mask": ... , "labels": ... , "input_pos": ... },
	...
]


def mem_packs(packs):
    total_size = 0
    for pack in packs:
        for elem in pack.values():
            total_size += sys.getsizeof(elem) + elem.element_size() * elem.nelement()
    return f"{round(total_size / (1024**3), 2)}G"
```

**Comment by joecummings** [comment]
See comment soln seems to be to calculate mask in each batch: https://github.com/pytorch/torchtune/pull/1083/files#diff-d069dcb7c967a8f3aaaca697349854143ff7b0631f885a6e7bd62dda19f6eee1R169

We could also technically do this for `input_pos`. This would slow down the processing but save memory:

```
tokens: 88 (fixed size of Python object) + 8 (size of torch.int64) * 3072 (max seq len)
labels: 88 + 8  * 3072
----------------------
49328 bytes ~= 0.05 MB
```

**Comment by SalmanMohammadi** [comment]
after discussing on github this needs to be updated so atnn masks are bool, not floats, but the idea is the same.
