### ISSUE TITLE
Was Pure bfloat16 or MixedPrecision bfloat16 Used for LLama3 pre-training?

### ISSUE THREAD

**Issue by jasonkrone** [pytorch/torchtune#1104]
Hi there, 

I noticed that the [full finetune distributed script](https://github.com/pytorch/torchtune/issues/new) uses pure bfloat16 training. Does that match the pre-training setting for Llama3 i.e. was Llama3 trained with pure bfloat16 rather than MixedPrecision bfloat16?

Here by Pure bfloat16 I mean that all computations are done in bfloat16, whereas for MixedPrecision bfloat16 the optimizer keeps a fp32 copy of the model weights that are updated by optimizer.step(). 

Thank you for your work on the library - it's a great resource!

**Comment by ebsmothers** [comment]
Hi @jasonkrone thanks for creating the issue. Tbh I don't have too many insights into the pretraining details, I think the [official llama3 repo](https://github.com/meta-llama/llama3) may be a better place to ask this.
