### ISSUE TITLE
Missing non-LoRA key tok_embeddings.weight from base model dict

### ISSUE THREAD

**Issue by vasicvuk** [pytorch/torchtune#1110]
When running following commands:

```sh
  File "/opt/Projects/torchtune/venv/lib/python3.10/site-packages/recipes/lora_finetune_single_device.py", line 302, in _setup_model
    validate_missing_and_unexpected_for_lora(
  File "/opt/Projects/torchtune/venv/lib/python3.10/site-packages/torchtune/modules/peft/peft_utils.py", line 334, in validate_missing_and_unexpected_for_lora
    raise AssertionError(f"Missing non-LoRA key {k} from base model dict")
AssertionError: Missing non-LoRA key tok_embeddings.weight from base model dict
```

I am getting error:
```
AssertionError: Missing non-LoRA key tok_embeddings.weight from base model dict
```

Is there something I am doing wrong?

**Comment by RdoubleA** [comment]
Hi @vasicvuk, which model are you using? Do you mind sharing your config?

**Comment by vasicvuk** [comment]
@RdoubleA phi3 with the config from the repo, I guess there is some extra steps about weights to do for phi3?

**Comment by david4096** [comment]
I had the same problem when trying the gemma-2b recipe

```
tune download google/gemma-2b --output-dir chk --hf-token $TOKEN--ignore-patterns ""
tune run lora_finetune_single_device --config 2B_lora_single_device.yaml \
dataset=torchtune.datasets.text_completion_dataset dataset.source=text \
dataset.data_files=path/to/my_data.txt dataset.split=train
```

**Comment by felipemello1** [comment]
@david4096 also not able to reproduce with the code below :/

```
tune run lora_finetune_single_device --config gemma/2B_lora_single_device dataset._component_=torchtune.datasets.wikitext_dataset
```

**Comment by habibregask86** [comment]
I'm having the same issue, following yaml file and tune command:

`batch_size: 4
dataset:
  path: ./torchtune_Dir/data/formatted_dataset.jsonl
dtype: bf16
seed: 42
epochs: 20
metric_logger:
  _component_: torchtune.training.metric_logging.WandBLogger
checkpointer:
    _component_: torchtune.training.FullModelHFCheckpointer
    checkpoint_dir: /home/azureuser/.cache/huggingface/hub/models--meta-llama--Meta-Llama-3-8B/snapshots/8cde5ca8380496c9a6cc7ef3a8b46a0372a1d920/
    checkpoint_files: []
    recipe_checkpoint: null
    resume_from_checkpoint: false
    output_dir: ./torchtune_Dir/outputs/
    model_type: LLAMA3
    should_load_recipe_state: false

resume_from_checkpoint: false
max_steps_per_epoch: 200
eval_steps: 200
fsdp:
  activation_checkpointing: true
  cpu_offload: false
  enabled: true
  fsdp_policy: transformer
  mixed_precision: true
  sharding_strategy: FULL_SHARD
gradient_accumulation_steps: 8
learning_rate: 0.001
logging_steps: 10
lr_scheduler_type: linear
max_sequence_length: 2048
max_steps: 1000
model:
  _component_: torchtune.models.llama3_1.lora_llama3_1_8b
  lora_rank: 64
  lora_alpha: 16
  lora_dropout: 0.05
  lora_attn_modules: ["q_proj", "v_proj", "k_proj", "o_proj"]
  apply_lora_to_mlp: false
  apply_lora_to_output: false
model_name: /home/azureuser/.cache/huggingface/hub/models--meta-llama--Meta-Llama-3-8B#./torchtune_Dir/models/Meta-Llama-3-8B
output_dir: ./torchtune_Dir/outputs
device: "cuda"
report_to: wandb
save_steps: 200
wandb:
  name: llama3-torch-run1
  project: torchtune-llama3-finetune
warmup_steps: 10
`

with the command: `tune run --nproc_per_node 2 lora_finetune_distributed --config ./torchtune_Dir/configs/llama3_finetune.yaml`

**Comment by felipemello1** [comment]
hey @habibregask86 , i would advise to print the state_dict keys and check whats in there. The errors says that its missing the embeddings.

**Comment by felipemello1** [comment]
As a sanity check, you can try running a default config and change it step by step until you figure out whats breaking
