### ISSUE TITLE
HF to Tune wrapper

### ISSUE THREAD

**Issue by ScottHoang** [pytorch/torchtune#1116]
Hi all, 
Thank you all for your fabulous work so far! I am having an enjoyable time working with the Torchtune framework. 
Currently, I am fine-tuning models outside what is currently supported. Is there any plan to produce an HFtoTune model wrapper without directly having to map HF to tune weights?
In my use cases, I make direct modifications to the HF model's structures, fine-tune them, and save them as is, so it would be great if I can wrap HF's model and tokenizer to work with Torchtune fine-tune recipe directly.

**Comment by joecummings** [comment]
Hey @ScottHoang !

That's an interesting use case - let me start by saying that right now, this isn't something we're thinking of enabling in the short term. However, we **do** plan on expanding our support for off-ramps into HF and other frameworks like [axolotl](https://github.com/OpenAccess-AI-Collective/axolotl/) by:

* Making it super easy to save models in a format that can be loaded by the Hugging Face `from_pretrained` API and upload to the Hugging Face Hub
* Working with brilliant people like @winglian (creator of axolotl) to enable users to use the best of both libraries functionalities

I'm curious to learn more about your process though. What do you like about modifying HF model's structures directly?

**Comment by ScottHoang** [comment]
Hi Joe, 
Thank you for your response!!
I am interested in layer-skipping by deleting redundant layers and fine-tuning inserted adaptors in my use cases!
