### ISSUE TITLE
Changing Linear layer to ParamList cause significant increase in memory usage in Llama3-8B LoRA fine-tuning.

### ISSUE THREAD

**Issue by MinghaoYan** [pytorch/torchtune#1153]
Hi,

I am modifying the lora_llama3_8b recipe to support multi-lora training. I found that if I change lora_b from a Linear layer to a ModuleList of Linear layers or a ParamList like this, this would result in OOM even if I reduce the batchsize, lora_rank, and gradient_accumulation_steps by a total of 100x.

```
# self.lora_b = nn.Linear(in_features=self.rank[0], out_features=out_dim, bias=False)
  self.lora_b = nn.ParameterList([
            nn.Parameter(torch.zeros(r, out_dim)) for r in self.rank
        ])
```

Hardware: 8* 40GB A100 GPUs

I am wondering if this is due to how FSDP handles a ModuleList/ParamList, since the underlying computation is largely unchanged, using multiple lora adapters is equivalent to increasing the batchsize dimension when computing attention (which is also how I implemented it). Once I switch from ParamList back to Linear, all OOM errors disappeared. Also, I noticed that when I use ParamList instead of Linear, I need to set use_orig_param to True due to the known "Must flatten tensors with uniform requires_grad when use_orig_params=False" issue https://github.com/pytorch/pytorch/issues/100945. 

Any ideas on how I can fix this?

Thank you!

**Comment by MinghaoYan** [comment]
I am wondering if this is related to pytorch/pytorch#113794

**Comment by ebsmothers** [comment]
Hi @MinghaoYan I just got to this. I see you closed the issue; out of curiosity how were you able to resolve it?

**Comment by MinghaoYan** [comment]
It was a bug on my end in the forward pass. But what made me think it might be the wrapper's problem was that when I initialize with ParamList, the GPU peak memory logged by the logger before training started (so supposedly my bug in the forward function should not affect it?) was higher than normal.
