### ISSUE TITLE
lm-eval==0.4.3 breaks euleuther_eval.py script 

### ISSUE THREAD

**Issue by ScottHoang** [pytorch/torchtune#1154]
Cannot make this import:
from lm_eval.evaluator import evaluate

It still works with lm-eval==0.4.2

**Comment by joecummings** [comment]
Hmm not sure what's going on here. Our recipe tests actually check (and pass) with `lm-eval==0.4.3` as you can see here: 
<img width="1321" alt="Screenshot 2024-07-09 at 2 56 46 PM" src="https://github.com/pytorch/torchtune/assets/20175092/224ff153-886b-4c67-a455-876cae01f87b">.

Can you provide the entire error trace and also try with fresh install?

**Comment by ScottHoang** [comment]
@joecummings super odd. Uninstall and reinstall torchtune, and lm-eval is now working.... Perhaps i was on an older torchtune version....
