### ISSUE TITLE
Checkpoint save in FSDP2 recipe hangs on 4 devices but not on 2 devices

### ISSUE THREAD

**Issue by ebsmothers** [pytorch/torchtune#1175]
First install PyTorch nightlies. Then run

```
tune run --nnodes=1 --nproc-per-node=2 lora_finetune_fsdp2 --config llama2/7B_lora \
gradient_accumulation_steps=1 max_steps_per_epoch=10
```

The above succeeds and saves a checkpoint. But if we instead run

```
tune run --nnodes=1 --nproc-per-node=4 lora_finetune_fsdp2 --config llama2/7B_lora \
gradient_accumulation_steps=1 max_steps_per_epoch=10
```

we get a hang on checkpoint save.

**Comment by ebsmothers** [comment]
cc @weifengpy @pbontrager

**Comment by weifengpy** [comment]
interesting! are you running on a devgpu? A100 or H100? I know some devgpu A100 specific issue so want to check first before deep dive

**Comment by ebsmothers** [comment]
8x A100 dev GPU. Do you think the NCCL config issue could be the cause here?

**Comment by weifengpy** [comment]
> 8x A100 dev GPU. Do you think the NCCL config issue could be the cause here?

will try reproducing it from my devgpu and check the stacktrace. hanging at local devgpu is debuggable

**Comment by ebsmothers** [comment]
Discussed offline, needed to change some config that is unique to our internal A100 devservers so this is actually not a broader issue. Thanks so much @weifengpy for solving this so quickly!
