### ISSUE TITLE
Error loading state dict using llama3_lora for inference

### ISSUE THREAD

**Issue by oliviernabuio** [pytorch/torchtune#1188]
Using torchtune nightly version, I finetuned a lora_llama3_8b model using some modification of the base config.
I created a config for generation replacing the checkpoint part with:
```
checkpointer:
  _component_: torchtune.utils.FullModelMetaCheckpointer
  checkpoint_dir: tune_output/
  checkpoint_files: [
    meta_model_1.pt
  ]
  adapter_checkpoint: adapter_1.pt
  recipe_checkpoint: recipe_state.pt
  model_type: LLAMA3
  output_dir: tune_output/
```
Got an error:
```
RuntimeError: Error(s) in loading state_dict for TransformerDecoder:
	Missing key(s) in state_dict: "layers.0.attn.q_proj.lora_a.weight", "layers.0.attn.q_proj.lora_b.weight", "layers.0.attn.v_proj.lora_a.weight", "layers.0.attn.v_proj.lora_b.weight", "layers.1.attn.q_proj.lora_a.weight", "layers.1.attn.q_proj.lora_b.weight", "layers.1.attn.v_proj.lora_a.weight", "layers.1.attn.v_proj.lora_b.weight", "layers.2.attn.q_proj.lora_a.weight", "layers.2.attn.q_proj.lora_b.weight", "layers.2.attn.v_proj.lora_a.weight", "layers.2.attn.v_proj.lora_b.weight", "layers.3.attn.q_proj.lora_a.weight", "layers.3.attn.q_proj.lora_b.weight", "layers.3.attn.v_proj.lora_a.weight", "layers.3.attn.v_proj.lora_b.weight", "layers.4.attn.q_proj.lora_a.weight", "layers.4.attn.q_proj.lora_b.weight", "layers.4.attn.v_proj.lora_a.weight", "layers.4.attn.v_proj.lora_b.weight", "layers.5.attn.q_proj.lora_a.weight", "layers.5.attn.q_proj.lora_b.weight", "layers.5.attn.v_proj.lora_a.weight", "layers.5.attn.v_proj.lora_b.weight", "layers.6.attn.q_proj.lora_a.weight", "layers.6.attn.q_proj.lora_b.weight", "layers.6.attn.v_proj.lora_a.weight", "layers.6.attn.v_proj.lora_b.weight", "layers.7.attn.q_proj.lora_a.weight", "layers.7.attn.q_proj.lora_b.weight", "layers.7.attn.v_proj.lora_a.weight", "layers.7.attn.v_proj.lora_b.weight", "layers.8.attn.q_proj.lora_a.weight", "layers.8.attn.q_proj.lora_b.weight", "layers.8.attn.v_proj.lora_a.weight", "layers.8.attn.v_proj.lora_b.weight", "layers.9.attn.q_proj.lora_a.weight", "layers.9.attn.q_proj.lora_b.weight", "layers.9.attn.v_proj.lora_a.weight", "layers.9.attn.v_proj.lora_b.weight", "layers.10.attn.q_proj.lora_a.weight", "layers.10.attn.q_proj.lora_b.weight", "layers.10.attn.v_proj.lora_a.weight", "layers.10.attn.v_proj.lora_b.weight", "layers.11.attn.q_proj.lora_a.weight", "layers.11.attn.q_proj.lora_b.weight", "layers.11.attn.v_proj.lora_a.weight", "layers.11.attn.v_proj.lora_b.weight", "layers.12.attn.q_proj.lora_a.weight", "layers.12.attn.q_proj.lora_b.weight", "layers.12.attn.v_proj.lora_a.weight", "layers.12.attn.v_proj.lora_b.weight", "layers.13.attn.q_proj.lora_a.weight", "layers.13.attn.q_proj.lora_b.weight", "layers.13.attn.v_proj.lora_a.weight", "layers.13.attn.v_proj.lora_b.weight", "layers.14.attn.q_proj.lora_a.weight", "layers.14.attn.q_proj.lora_b.weight", "layers.14.attn.v_proj.lora_a.weight", "layers.14.attn.v_proj.lora_b.weight", "layers.15.attn.q_proj.lora_a.weight", "layers.15.attn.q_proj.lora_b.weight", "layers.15.attn.v_proj.lora_a.weight", "layers.15.attn.v_proj.lora_b.weight", "layers.16.attn.q_proj.lora_a.weight", "layers.16.attn.q_proj.lora_b.weight", "layers.16.attn.v_proj.lora_a.weight", "layers.16.attn.v_proj.lora_b.weight", "layers.17.attn.q_proj.lora_a.weight", "layers.17.attn.q_proj.lora_b.weight", "layers.17.attn.v_proj.lora_a.weight", "layers.17.attn.v_proj.lora_b.weight", "layers.18.attn.q_proj.lora_a.weight", "layers.18.attn.q_proj.lora_b.weight", "layers.18.attn.v_proj.lora_a.weight", "layers.18.attn.v_proj.lora_b.weight", "layers.19.attn.q_proj.lora_a.weight", "layers.19.attn.q_proj.lora_b.weight", "layers.19.attn.v_proj.lora_a.weight", "layers.19.attn.v_proj.lora_b.weight", "layers.20.attn.q_proj.lora_a.weight", "layers.20.attn.q_proj.lora_b.weight", "layers.20.attn.v_proj.lora_a.weight", "layers.20.attn.v_proj.lora_b.weight", "layers.21.attn.q_proj.lora_a.weight", "layers.21.attn.q_proj.lora_b.weight", "layers.21.attn.v_proj.lora_a.weight", "layers.21.attn.v_proj.lora_b.weight", "layers.22.attn.q_proj.lora_a.weight", "layers.22.attn.q_proj.lora_b.weight", "layers.22.attn.v_proj.lora_a.weight", "layers.22.attn.v_proj.lora_b.weight", "layers.23.attn.q_proj.lora_a.weight", "layers.23.attn.q_proj.lora_b.weight", "layers.23.attn.v_proj.lora_a.weight", "layers.23.attn.v_proj.lora_b.weight", "layers.24.attn.q_proj.lora_a.weight", "layers.24.attn.q_proj.lora_b.weight", "layers.24.attn.v_proj.lora_a.weight", "layers.24.attn.v_proj.lora_b.weight", "layers.25.attn.q_proj.lora_a.weight", "layers.25.attn.q_proj.lora_b.weight", "layers.25.attn.v_proj.lora_a.weight", "layers.25.attn.v_proj.lora_b.weight", "layers.26.attn.q_proj.lora_a.weight", "layers.26.attn.q_proj.lora_b.weight", "layers.26.attn.v_proj.lora_a.weight", "layers.26.attn.v_proj.lora_b.weight", "layers.27.attn.q_proj.lora_a.weight", "layers.27.attn.q_proj.lora_b.weight", "layers.27.attn.v_proj.lora_a.weight", "layers.27.attn.v_proj.lora_b.weight", "layers.28.attn.q_proj.lora_a.weight", "layers.28.attn.q_proj.lora_b.weight", "layers.28.attn.v_proj.lora_a.weight", "layers.28.attn.v_proj.lora_b.weight", "layers.29.attn.q_proj.lora_a.weight", "layers.29.attn.q_proj.lora_b.weight", "layers.29.attn.v_proj.lora_a.weight", "layers.29.attn.v_proj.lora_b.weight", "layers.30.attn.q_proj.lora_a.weight", "layers.30.attn.q_proj.lora_b.weight", "layers.30.attn.v_proj.lora_a.weight", "layers.30.attn.v_proj.lora_b.weight", "layers.31.attn.q_proj.lora_a.weight", "layers.31.attn.q_proj.lora_b.weight", "layers.31.attn.v_proj.lora_a.weight", "layers.31.attn.v_proj.lora_b.weight". 
```
It seems the expected dictionnary key for loading are different from those that are saved?

**Comment by oliviernabuio** [comment]
Is there any plan to add the lora loading in the inference recipe (using the setup model from the lora_training_recipe)?
```
    def _setup_model(
        self,
        cfg_model: DictConfig,
        enable_activation_checkpointing: bool,
        compile_model: bool,
        base_model_state_dict: Dict[str, Any],
        lora_weights_state_dict: Optional[Dict[str, Any]] = None,
    ) -> nn.Module:
        with utils.set_default_dtype(self._dtype), self._device:
            model = config.instantiate(cfg_model)

        self._lora_rank = cfg_model.lora_rank
        self._lora_alpha = cfg_model.lora_alpha
        self._lora_attn_modules = list(cfg_model.lora_attn_modules)
        self._apply_lora_to_mlp = cfg_model.apply_lora_to_mlp
        self._apply_lora_to_output = getattr(cfg_model, "apply_lora_to_output", False)
        self.adapter_params = get_adapter_params(model)
        set_trainable_params(model, self.adapter_params)

        if enable_activation_checkpointing:
            utils.set_activation_checkpointing(
                model, auto_wrap_policy={modules.TransformerDecoderLayer}
            )

        base_missing, base_unexpected = model.load_state_dict(
            base_model_state_dict, strict=False
        )
        if lora_weights_state_dict:
            lora_missing, lora_unexpected = model.load_state_dict(
                lora_weights_state_dict, strict=False
            )
        else:
            lora_missing, lora_unexpected = None, None
        validate_missing_and_unexpected_for_lora(
            lora_attn_modules=self._lora_attn_modules,
            apply_lora_to_mlp=self._apply_lora_to_mlp,
            apply_lora_to_output=self._apply_lora_to_output,
            base_missing=base_missing,
            base_unexpected=base_unexpected,
            lora_missing=lora_missing,
            lora_unexpected=lora_unexpected,
        )
        # Validate model adapter params were loaded in with the expected dtype
        # TODO (rohan-varma): Further validation to ensure the appropriate base params
        # are NF4 vs bf16 based on the quantization config.
        utils.validate_expected_param_dtype(
            self.adapter_params.items(), dtype=self._dtype
        )

        log.info(f"Model is initialized with precision {self._dtype}.")
        # Compile model, if enabled.
        if compile_model:
            log.info("Compiling model with torch.compile...")
            backend = os.environ.get("TORCH_COMPILE_BACKEND", "inductor")
            model.compile(backend=backend)
        if self._device.type == "cuda":
            memory_stats = utils.get_memory_stats(device=self._device)
            utils.log_memory_stats(memory_stats)
        return model
```

**Comment by joecummings** [comment]
Hey @oliviernabuio  - this is definitely a gap in our documentation, thanks for bringing it to our attention. 

When you train on LoRA, we save both the merged weights and the adapter weights. The adapter weights can be loaded into the PEFT library or used for further train. But for generation, you can point just to the finetuned merged weights like you are doing in the checkpointer. Since we are not "LoRA-fying" these weights anymore, you should just be loading them into the base model. So the following would work for your generation case:

```yaml
model:
  _component_: torchtune.models.llama3.llama3_8b

tokenizer:
  _component_: torchtune.models.llama3.llama3_tokenizer
  path: /path/to/tokenizer.model

checkpointer:
  _component_: torchtune.utils.FullModelMetaCheckpointer
  checkpoint_dir: tune_output/
  checkpoint_files: [
    meta_model_1.pt
  ]
  model_type: LLAMA3
  output_dir: tune_output/
```

**Comment by pbontrager** [comment]
When you run the LoRA recipe it merges the LoRA weights into the checkpoint on save checkpoint. It also saves the adapter weights separately so you can maintain a smaller checkpoint if you want. I believe in your case, you might have merged the LoRA weights into an already merged checkpoint.

That being said, we should likely support being able to load in adapter weights that are unmerged into generate as well. We should probably have a way to make it clear when checkpoints are already merged. @joecummings

**Comment by oliviernabuio** [comment]
So, you should actually use a llama3_8b model for inference in the config?

**Comment by oliviernabuio** [comment]
> Hey @oliviernabuio - this is definitely a gap in our documentation, thanks for bringing it to our attention.
> 
> When you train on LoRA, we save both the merged weights and the adapter weights. The adapter weights can be loaded into the PEFT library or used for further train. But for generation, you can point just to the finetuned merged weights like you are doing in the checkpointer. Since we are not "LoRA-fying" these weights anymore, you should just be loading them into the base model. So the following would work for your generation case:
> 
> ```yaml
> model:
>   _component_: torchtune.models.llama3.llama3_8b
> 
> tokenizer:
>   _component_: torchtune.models.llama3.llama3_tokenizer
>   path: /path/to/tokenizer.model
> 
> checkpointer:
>   _component_: torchtune.utils.FullModelMetaCheckpointer
>   checkpoint_dir: tune_output/
>   checkpoint_files: [
>     meta_model_1.pt
>   ]
>   model_type: LLAMA3
>   output_dir: tune_output/
> ```

There is something I don't understand then, then what is the point in the config to indicate the path to the adapter weight instead of having a flag (when resuming training, since given the current code, it is directly loaded from the checkpoint file):
```
        # log config with parameter override
        self._metric_logger.log_config(cfg)

        self._model_compile = cfg.compile
        checkpoint_dict = self.load_checkpoint(cfg_checkpointer=cfg.checkpointer)

        self._model = self._setup_model(
            cfg_model=cfg.model,
            enable_activation_checkpointing=cfg.enable_activation_checkpointing,
            compile_model=cfg.compile,
            base_model_state_dict=checkpoint_dict[utils.MODEL_KEY],
            lora_weights_state_dict=(
                checkpoint_dict[utils.ADAPTER_KEY]
                if self._resume_from_checkpoint
                else None
            ),
        )
```
After question I have: 
If given for example two epoch, then you get: 
- adapter_0
- adapter_1
- meta_model_0
- meta_model_1
Then you have meta_model_1 = base_model+adapter_0+adapter_1 = meta_model_0+adapter_1?

**Comment by pbontrager** [comment]
> Doesn't that mean that if you resume training, you are loading the lora weight twice, (if using default config for resume):

Resume from checkpoint will load in the base weights and the adapter, not the merged weights.

> Then you have meta_model_1 = base_model+adapter_0+adapter_1 = meta_model_0+adapter_1?

You can't add adapters together to equal a future adapter. model_0 = base + adapter_0 and model_1 = base + adapter_1

**Comment by oliviernabuio** [comment]
> > Doesn't that mean that if you resume training, you are loading the lora weight twice, (if using default config for resume):
> 
> Resume from checkpoint will load in the base weights and the adapter, not the merged weights.
> 
> > Then you have meta_model_1 = base_model+adapter_0+adapter_1 = meta_model_0+adapter_1?
> 
> You can't add adapters together to equal a future adapter. model_0 = base + adapter_0 and model_1 = base + adapter_1

Yeah, just saw that in the documentation, i got confused with the full finetune and the lorafinetune config.

**Comment by EllaWang18** [comment]
> When you train on LoRA, we save both the merged weights and the adapter weights. The adapter weights can be loaded into the PEFT library or used for further train. But for generation, you can point just to the finetuned merged weights like you are doing in the checkpointer. Since we are not "LoRA-fying" these weights anymore, you should just be loading them into the base model.

@joecummings I am not sure whether this is the case. I fine-tuned a Llama LoRA model via `tune run lora_finetune_single_device`, the output folder looks like this: 
<img width="223" alt="Screenshot 2024-11-19 at 4 47 58 PM" src="https://github.com/user-attachments/assets/951ce6f7-df74-4d65-8875-7a10c32e045b">

There is no file with the "merged" weights:  `hf_model_0001_*.pt` only saves the base model weights; `adapter_model.bin` and `adpater_*.pt` files only save LoRA weights.

Maybe I misunderstood. Would appreciate any explanation.

**Comment by ebsmothers** [comment]
@EllaWang18 thanks for the comment. The files `hf_model_0001_*.pt` should contain the merged weights -- you can see e.g. [here](https://github.com/pytorch/torchtune/blob/abdb5a43c1173cdb05208ca6fd498919536c4c19/recipes/lora_finetune_single_device.py#L605-L611) that the weights are merged into the "model" key of the state_dict, which is then processed into the HF format and saved into the filename you see [here](https://github.com/pytorch/torchtune/blob/abdb5a43c1173cdb05208ca6fd498919536c4c19/torchtune/training/checkpointing/_checkpointer.py#L611-L623).
