### ISSUE TITLE
`wikitext_dataset` fails in model forward with "Expected Long, Int; but got torch.cuda.FloatTensor"

### ISSUE THREAD

**Issue by RdoubleA** [pytorch/torchtune#1191]
Thanks to @felipemello1 for pointing this out.

Repro: `tune run lora_finetune_single_device --config llama3/8B_lora_single_device max_seq_len=4096 dataset=torchtune.datasets.wikitext_dataset gradient_accumulation_steps=2 log_every_n_steps=1 log_peak_memory_stats=True max_steps_per_epoch=10 epochs=1`

Because the wikitext dataset (https://huggingface.co/datasets/Salesforce/wikitext) splits samples by line in an article, some of the rows will be empty, leading to entire samples with pad_id. Ideally, these rows should just be dropped.

But this leads to our bug - if the first sample is empty, `pad_sequence` in `padded_collate` will actually return a FloatTensor instead of keeping the ints (https://github.com/pytorch/torchtune/blob/main/torchtune/utils/collate.py#L46). You can repro this adding `pdb.set_trace()` above the linked code and continuing until you see a batch where the first sample is empty.

The fix is twofold:
- Enforce int tensors with `long()` in collate
- Use the document level version of wikitext: https://huggingface.co/datasets/EleutherAI/wikitext_document_level, which is a cleaner dataset

**Comment by pbontrager** [comment]
Can you just modify wikitext_dataset itself to skip empty sequences? My concern with `long` is that it won't respect the int type used by the other tokens.

**Comment by RdoubleA** [comment]
addressed in #1258
