### ISSUE TITLE
Converting megatron model architecture to torchtune

### ISSUE THREAD

**Issue by eghouti** [pytorch/torchtune#1206]
Hello,

I want to convert a megatron model architecture (not only the weight) to torchtune. Is there a fast/easy way to do it?

**Comment by ebsmothers** [comment]
Hi @eghouti thanks for creating the issue. Can you clarify what you mean by converting the architecture? These are all just nn.Modules so there is probably no general mapping between them (forwards, instance variables, etc can differ). So the standard thing to do would be to take a set of weights from a Megatron model, remap them into a torchtune-supported format, and then load into a torchtune model. If you give a specific example of what you have in mind I can try to provide more detailed suggestions though

**Comment by SalmanMohammadi** [comment]
To add to @ebsmothers's suggestion, depending on the architecture, another path of least resistance might be going through HuggingFace's `transformers`, if the model you're interested in is supported and has conversion utilities.

For example, if you're interested in converting GPT2, you could:
1) Converting your megatron GPT2 checkpoint into a HF checkpoint (see [here](https://github.com/huggingface/transformers/blob/main/src/transformers/models/megatron_gpt2/convert_megatron_gpt2_checkpoint.py) for a conversion script). This will give you a HF-style checkpoint for a GPT2 model. 
2) You'll need to implement a component builder for a GPT model into torchtune. 
3) You can now (hopefully) use our built-in checkpointers to load the converted checkpoint from step 1. into your torchtune GPT!
4) $$ profit $$ 

You can skip step 2. if the model already exists in torchtune - you could just rely on HF's conversion utilities and then load directly into one of our models!
