### ISSUE TITLE
Doc error for text_completion_dataset 

### ISSUE THREAD

**Issue by troy256** [pytorch/torchtune#1226]
The documentatoin at https://pytorch.org/torchtune/stable/tutorials/datasets.html indicates that when using the unmodified text_completion_dataset type, there is a parameter **dataset.source** which describes the dataset type (E.g. - text) and a **dataset.data_files** parameter, which points to the actual local dataset.

In the current version it seems as if **dataset.source** replaced **dataset.data_files** and points to the actual local dataset.  Also there doesn't seem to be a specific parameter to set dataset type, as it appears to be automatically determined.

**Comment by ebsmothers** [comment]
Hi @troy256 thanks for creating this issue. Assigning to @RdoubleA to take a look here

**Comment by RdoubleA** [comment]
Hey @troy256, you can still pass in source and data_files into `text_completion_dataset` exactly as you suggested, where source is the data file type and data_files is the actual path. I do see where the confusion is, the docstring for the source parameter only discusses path to a HF dataset. I can make this docstring more clear.
