### ISSUE TITLE
ImportError: cannot import name 'return_and_correct_aliasing' from 'torch.utils._python_dispatch'

### ISSUE THREAD

**Issue by badarrrr** [pytorch/torchtune#1259]
![image](https://github.com/user-attachments/assets/af4ac08c-5879-45cb-8789-cab1e3750c73)

I met this error when running `tune --help` 

Torch version: 2.1.1+cu121
Torchvision version: 0.16.1+cu121

**Comment by Elllllllvin** [comment]
upgrade pytorch version to 2.3.0

**Comment by badarrrr** [comment]
Thanks!

**Comment by WAS-PlaiLabs** [comment]
Problem is back in Torch 2.4.0.
