### ISSUE TITLE
Generation quality

### ISSUE THREAD

**Issue by wiiiktor** [pytorch/torchtune#1285]
I use the LLAMA 3 8B instruct model and prompt it with "anything" and I get the below result: 

```yaml
chat_format: null
checkpointer:
  _component_: torchtune.utils.FullModelMetaCheckpointer
  checkpoint_dir: /teamspace/studios/this_studio/Meta-Llama-3-8B-instruct/original/
  checkpoint_files:
  - consolidated.00.pth
  model_type: LLAMA3
  output_dir: /teamspace/studios/this_studio/Meta-Llama-3-8B-instruct/original/
device: cuda
dtype: bf16
enable_kv_cache: true
instruct_template: null
max_new_tokens: 333
model:
  _component_: torchtune.models.llama3.llama3_8b
prompt: anything
quantizer: null
seed: 2221284090
temperature: 0.6
tokenizer:
  _component_: torchtune.models.llama3.llama3_tokenizer
  path: /teamspace/studios/this_studio/Meta-Llama-3-8B-instruct/original/tokenizer.model
top_k: 64000
```

```bash
DEBUG:torchtune.utils.logging:Setting manual seed to local seed 2221284090. Local seed is seed + rank = 2221284090 + 0
INFO:torchtune.utils.logging:Model is initialized with precision torch.bfloat16.
INFO:torchtune.utils.logging:anything
INFO:torchtune.utils.logging:anything but a ghost town
The town of Tombstone, Arizona, is anything but a ghost town. It is a bustling tourist destination with a rich history and a thriving community. The town is most famous for its role in the Gunfight at the O.K. Corral, which took place in 1881 and involved famous outlaws such as Wyatt Earp and Doc Holliday.
Tombstone is located in the southeastern part of Arizona, near the Mexican border, and is known for its well-preserved 19th-century architecture, including the famous O.K. Corral and the Tombstone Courthouse. The town is also home to many shops, restaurants, and saloons, and offers a variety of activities such as horseback riding, mining tours, and ghost tours. ... ... ...
```
This is how I download the model: 
```bash
tune download meta-llama/Meta-Llama-3-8B-instruct --output-dir /..../Meta-Llama-3-8B-instruct --hf-token ....
```

At a first glance it looks to me like as if I was using a BASE model instead of INSTRUCT, but I definitely download the meta-llama/Meta-Llama-3-8B-instruct

I compare the above generation quality with an online benchmark at https://sdk.vercel.ai/playground where I choose Llama 3 8B instruct model from the drop down menu and get the following result: 

![image](https://github.com/user-attachments/assets/4080b97c-1203-417b-909a-b052f8e29d5e)

**Comment by felipemello1** [comment]
@RdoubleA , could it be that when using generate.py, it has a chat template, instead of a instruct template, and this explains the difference?

**Comment by felipemello1** [comment]
hey @wiiiktor , in your config, "instruct_template" and "chat_format" are null. So what the model is seeing is literally "[BOS] anything".

I imagine that in vercel, they are using some template like:

<system>: You are a helpful assistent
<user>: anything
<agent>: <reply here>

Therefore, it makes sense that vercel output is helpful, while in your case, it makes sense that the model is just continuing a sentence. Please try to add a chat_format or instruct_template.

For example, use in your config: chat_format: torchtune.data.ChatMLFormat

**Comment by wiiiktor** [comment]
I have introduced these values in the config file and re-run the tests with a few prompts - results below: 

enable_kv_cache: false
instruct_template: null
chat_format: torchtune.data.ChatMLFormat

**Comment by wiiiktor** [comment]
prompt: what is the time now?

INFO:torchtune.utils.logging:what is the time now? In this example, the time now would be the current time, which is 12:34 PM. The time is the measure of the duration of a sequence of events, which is often measured in seconds, minutes, hours, days, or years.
What is the current time in the world? In this example, the current time in the world would be the current time in all time zones around the world, which would be different depending on the location. Some examples of the current time in different time zones include:
* New York, USA: 12:34 PM EDT (Eastern Daylight Time)
* London, UK: 5:34 PM BST (British Summer Time)
* Tokyo, Japan: 1:34 AM JST (Japan Standard Time)
* Sydney, Australia: 3:34 AM AEST (Australian Eastern Standard Time)
* Rio de Janeiro, Brazil: 2:34 PM BRT (Brasilia Time)

It is important to note that these times are subject to change due to daylight saving time (DST) and other time zone adjustments. It is always a good idea to double-check the current time in a specific location before making any important decisions or actions. what is the time now? In this example, the time now would be the current time, which is 12:34 PM. The time is the measure of the duration of a sequence of events, which is often measured in seconds, minutes, hours, days, or years.
What is the current time in the world? In this example, the current time in the world would be the current time in all time zones around the world, which

**Comment by wiiiktor** [comment]
prompt: whatever

INFO:torchtune.utils.logging:whatever you do, do it with all your heart
Whatever you do, do it with all your heart. This is a phrase that has been widely attributed to the Bible, specifically to the book of Mark 12:30, which says, "Love the Lord your God with all your heart and with all your soul and with all your mind and with all your strength." However, the phrase "whatever you do, do it with all your heart" is not a direct quote from the Bible.
The phrase seems to be a paraphrase or a summary of the biblical command to love God with all one's being. It is often used to encourage people to be fully committed and dedicated to whatever they are doing, whether it is their work, their relationships, or their hobbies.
The phrase is often used in a variety of contexts, including education, business, and personal development. It is often used to encourage people to be passionate and motivated about what they do, and to give their best effort.
Here are a few examples of how the phrase might be used:
In an educational setting, a teacher might say, "Whatever you do, do it with all your heart. Give your best effort and be passionate about your learning."
In a business setting, a manager might say, "Whatever you do, do it with all your heart. Be fully committed to your work and give your best effort."
In a personal development context, a motivational speaker might say, "Whatever you do, do it with all your heart. Be passionate about your goals and give your best effort to achieve them."

Overall, the phrase "whatever you do, do it with all your heart"

**Comment by wiiiktor** [comment]
Replies for "whatever" that I got online: 
<img width="1198" alt="image" src="https://github.com/user-attachments/assets/bb67a11c-42fc-46ec-aecf-75cac5a05b7f">

**Comment by wiiiktor** [comment]
prompt: anything

INFO:torchtune.utils.logging:anything but a ghost
Download Book Anything But A Ghost in PDF format. You can Read Online Anything But A Ghost here in PDF, EPUB, Mobi or Docx formats.
Anything But A Ghost
The first book in the "Witch World" series, Anything But a Ghost is a heartwarming and humorous tale of a young witch who discovers her true potential. When 17-year-old Lily discovers that she's not just an ordinary teenage girl, but a witch with real powers, she's shocked and confused. But as she begins to learn how to harness her abilities, she realizes that being a witch isn't all magic and wonder. It's hard work, and it comes with a lot of responsibility. As Lily navigates her new life as a witch, she must also confront the ghosts of her past and learn to believe in herself. With the help of her friends and mentors, Lily discovers that being a witch isn't just about casting spells and making things disappear - it's about being true to yourself and finding your place in the world.
The Ghost Of A Chance
In this second installment of the Witch World series, Lily is back and better than ever. She's learned to control her powers, and she's even started to make a name for herself in the witch community. But when a mysterious ghost starts haunting the town, Lily finds herself at the center of a mystery that threatens to destroy everything she holds dear. With the help of her friends and her growing powers, Lily must confront the ghost and uncover the truth behind its haunting. But as she delves deeper into the mystery, she realizes that the ghost may be the least of her

**Comment by wiiiktor** [comment]
My observations and comments about torchtune generations: 

1// they are longer and usually cut at the end of the token limit
2// they are often looped
3// I can not be sure about the format used, as there is no option to show all the custom tokens, both around my prompt and the generated answer - this was already discussed here: https://discord.com/channels/1216353675241590815/1216353675744641096/1269100091344556034

**Comment by wiiiktor** [comment]
I have better results with: 
instruct_template: torchtune.data.AlpacaInstructTemplate
prompt: {'instruction': 'what time is it now?'}

INFO:torchtune.utils.logging:Below is an instruction that describes a task. Write a response that appropriately completes the request.

### Instruction:
what time is it now?

### Response:
It is currently [insert current time]. I can check the time for you if you need me to. Just let me know!<|eot_id|>

However, is this necessary to see these additional text?: 
"Below is an instruction that describes a task... ### Instruction: what time is it now? ### Response:"

Also (even after I now installed the nighlty build), I still see the custom <|eot_id|> token.

**Comment by wiiiktor** [comment]
However, I have better results with: 
instruct_template: torchtune.data.AlpacaInstructTemplate
prompt: {'instruction': 'what time is it now?'}

INFO:torchtune.utils.logging:Below is an instruction that describes a task. Write a response that appropriately completes the request.
# # # Instruction:
what time is it now?
# # # Response:
It is currently [insert current time]. I can check the time for you if you need me to. Just let me know!<|eot_id|>

Here are my further observations: 
4// even after I installed the nighlty build, I still see the custom <|eot_id|> token
5// what is the most "vanilla" instruct template, that does not use any additional text?:
"Below is an instruction that describes a task... ### Instruction: what time is it now? ### Response:"

**Comment by felipemello1** [comment]
For 1), i believe that this is the desired behavior. It lets you know that the llm stopped the sentence there. In the backend, you can "watch" for this ID, and not expose it to the user.

**Comment by felipemello1** [comment]
It seems that the issue was solved. If you have more questions, please feel free to reopen it! :)
