### ISSUE TITLE
tune download should use HF_TOKEN env variable

### ISSUE THREAD

**Issue by msaroufim** [pytorch/torchtune#1293]
Instead of passing in `tune download --hf-token ...`

I want to just do `tune download ...`

It's nit but tedious to pass in the token each time so HF makes available an env variable `HF_TOKEN` which I've set in my `bashrc` so I never have to think about it

https://huggingface.co/docs/huggingface_hub/en/package_reference/environment_variables

Tested on this commit git checkout 52e328337579e9b84ba7f2448b29a6de7c5d8db3 feel free to close if fixed on main

**Comment by SalmanMohammadi** [comment]
If not set, it grabs the token from env I think? https://github.com/pytorch/torchtune/blob/52e328337579e9b84ba7f2448b29a6de7c5d8db3/torchtune/_cli/download.py#L87 on your commit and on main

Very silly questions: `echo $HF_TOKEN` and `python -c "import os; print(os.getenv('HF_TOKEN', None))"` both work?

**Comment by RdoubleA** [comment]
why not just use `huggingface-cli login`? I do that once and I never have to set `HF_TOKEN` again

**Comment by msaroufim** [comment]
Issue was an invalid token on my end. Sorry!
