### ISSUE TITLE
Catch proper `ImportError` if Weights & Biases is not installed as a package

### ISSUE THREAD

**Issue by joecummings** [pytorch/torchtune#1298]
**Objective**: We should communicate to the user precisely what the issue is if they try to use the `WandBLogger` and they have not installed the package yet.

**Current state**: This is the current error shown to the user if the package is not installed:
```bash
  File "/root/torchtune/torchtune/config/_instantiate.py", line 31, in _instantiate_node
    return _create_component(_component_, args, kwargs)
  File "/root/torchtune/torchtune/config/_instantiate.py", line 20, in _create_component
    return _component_(*args, **kwargs)
  File "/root/torchtune/torchtune/utils/metric_logging.py", line 177, in __init__
    raise ImportError(
ImportError: ``wandb`` package not found. Please install wandb using `pip install wandb` to use WandBLogger.Alternatively, use the ``StdoutLogger``, which can be specified by setting metric_logger_type='stdout'.
Exception ignored in: <function WandBLogger.__del__ at 0x7f99a9c60ca0>
Traceback (most recent call last):
  File "/root/torchtune/torchtune/utils/metric_logging.py", line 251, in __del__
    if self._wandb.run:
AttributeError: 'WandBLogger' object has no attribute '_wandb'
```

**Issue**: `ImportError` is obfuscated by the `AttributeError` that happens in the `__del__` method. 

**Fix**: Either catch the error in `__del__` method and allow it to pass through or confirm if we even need the `__del__` method at all.

**Comment by felipemello1** [comment]
I will add:

`if self._wandb and self._wandb.run:`

**Comment by joecummings** [comment]
@felipemello1 Are you planning on doing this? If so, I'll remove the `community help wanted` tag. Otherwise, I'll keep it for someone else to pick up.
