### ISSUE TITLE
Move `modules/loss` dir into `modules/rlhf/loss`

### ISSUE THREAD

**Issue by joecummings** [pytorch/torchtune#1299]
The losses in `modules/loss` only pertain to RLHF and belong logically in that directory.

**Comment by ChinoUkaegbu** [comment]
Hi, I'd like to work on this. Just a clarification, after moving the modules/loss dir into modules/rlhf/loss, would any references need to be updated?

**Comment by joecummings** [comment]
@ChinoUkaegbu Awesome! Thanks for picking this up. 

Yes, the [docs page](https://github.com/pytorch/torchtune/blob/main/docs/source/api_ref_modules.rst#loss) will need to be updated as well as the references to these losses in the DPO and PPO recipes/configs.
