### ISSUE TITLE
Duplicate logging

### ISSUE THREAD

**Issue by ebsmothers** [pytorch/torchtune#1302]
Should be relatively quick to debug but I may not get to it today.. seems like our logging is happening multiple times.

For example if I run
```
tune run lora_finetune_single_device --config llama3/8B_lora_single_device
```

the first part of my logs look like [this](https://gist.github.com/ebsmothers/b9d3a4b5254075e99540d71b845d3747).

My env is PyTorch + TorchVision stable install and dev install on torchtune main.

**Comment by joecummings** [comment]
Can you be explicit about the expected behavior? Then we can ask for community help on this.

**Comment by ebsmothers** [comment]
Updated

**Comment by ebsmothers** [comment]
Nvm something else is happening here. I am gonna seeing this running single-device recipes too. Gonna close this for now and debug more

**Comment by ebsmothers** [comment]
Updated this -- I'm actually seeing it on all recipes, not just distributed ones
