### ISSUE TITLE
add max_seq_len to configs

### ISSUE THREAD

**Issue by felipemello1** [pytorch/torchtune#1311]
In this PR (https://github.com/pytorch/torchtune/pull/1234) we changed where max_seq_len should be defined in the config.

Before, it was defined in dataset.max_seq_len, and then passed to the tokenizer:

datasets._instruct.py
```
        tokens, mask = self._tokenizer.tokenize_messages(
            messages, max_seq_len=self.max_seq_len
        )
```

But now, max_seq_len needs to be defined in the tokenizer.max_seq_len
```
 tokens, mask = self._tokenizer.tokenize_messages(
            messages,
        )
```

Task:
1) Update recipes/configs, so that this option is exposed, otherwise the training loop breaks and its not clear what the user should do (ValueError: seq_len (9274) of input tensor should be smaller than max_seq_len (8192));

e.g.
llama3.yaml
```
tokenizer:
	max_seq_len=None

```
2) remove max_seq_len from dataset args, since its not used. Another option is to raise some error if users pass dataset.max_seq_len instead. Code pointer of one of the datasets: https://github.com/RdoubleA/torchtune/blob/5c7246e05b56729324625dee8a886727cfefeac0/torchtune/datasets/_instruct.py#L56

3) add a better error message to let users know that they can update tokenizer.max_seq_len to avoid this issue. Pointer: https://github.com/RdoubleA/torchtune/blob/288ff4435b0cf17325b5c3b112f6859a6cdf0ea2/torchtune/modules/attention.py#L165;

cc: @RdoubleA

**Comment by joecummings** [comment]
@felipemello1  is this done?
