### ISSUE TITLE
tune download: error: An error happened while trying to locate the file on the Hub and we cannot find the requested files in the local cache. Please check your connection and try again or make sure your Internet connection is on.

### ISSUE THREAD

**Issue by waylonli** [pytorch/torchtune#1316]
Command:
`tune download meta-llama/Meta-Llama-3-8B-Instruct --output-dir ./tmp/llama3/`
Error:
```
Ignoring files matching the following patterns: *.safetensors
Fetching 13 files:   0%|                                                                                                                                 | 0/13 [00:00<?, ?it/s]
LICENSE: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7.63k/7.63k [00:00<00:00, 22.9MB/s]
README.md: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 40.9k/40.9k [00:00<00:00, 575kB/s]
usage: tune download <repo-id> [OPTIONS]
tune download: error: An error happened while trying to locate the file on the Hub and we cannot find the requested files in the local cache. Please check your connection and try again or make sure your Internet connection is on.
```

**Comment by joecummings** [comment]
Looks like the [repo is up](https://huggingface.co/meta-llama/Meta-Llama-3-8B-Instruct) and you passed in the correct name 👍

You might want to make sure you have a stable internet connection and try again in a little bit?

**Comment by waylonli** [comment]
> Looks like the [repo is up](https://huggingface.co/meta-llama/Meta-Llama-3-8B-Instruct) and you passed in the correct name 👍
> 
> You might want to make sure you have a stable internet connection and try again in a little bit?

Thanks for your reply. I tried it on my personal device, cloud server, and Google Colab. This error pops up on all the devices so I think it might not be the internet issue.

**Comment by SalmanMohammadi** [comment]
Works OK for me - have you been granted access to the model in HuggingFace, and set your HF tokens up correctly? You can either do `huggingface-cli` login or pass `--hf-token <HF_TOKEN>` to `tune download`.

**Comment by waylonli** [comment]
Thanks a lot for all the replies. The issue is due to the huggingface token permission.
