### ISSUE TITLE
Unable to install torchtune 0.2.1

### ISSUE THREAD

**Issue by Timelessprod** [pytorch/torchtune#1321]
Hello,

I tried to install `torchtune==0.2.1` on my Python 3.11 pyenv running on a Mac M1 (Sonoma) but it fails with the following error:

```
Collecting tiktoken (from torchtune==0.2.0->-r requirements.txt (line 5))
  Using cached tiktoken-0.7.0-cp311-cp311-macosx_11_0_arm64.whl.metadata (6.6 kB)
Collecting blobfile>=2 (from torchtune==0.2.0->-r requirements.txt (line 5))
  Using cached blobfile-2.1.1-py3-none-any.whl.metadata (15 kB)
Collecting omegaconf (from torchtune==0.2.0->-r requirements.txt (line 5))
  Using cached omegaconf-2.3.0-py3-none-any.whl.metadata (3.9 kB)
INFO: pip is looking at multiple versions of torchtune to determine which version is compatible with other requirements. This could take a while.
ERROR: Could not find a version that satisfies the requirement torchao==0.3.1 (from torchtune) (from versions: 0.0.1, 0.0.3, 0.1)
ERROR: No matching distribution found for torchao==0.3.1
```

Fyi this is the requirements file I used (I'm trying different frameworks at once to find one which is working with M1 architecture, thus there are a lot of different ones on the same env):
```
pandas==2.2.2
transformers[torch]==4.41.2
datasets==2.19.2
torch==2.4.0
torchtune==0.2.1
huggingface-hub==0.23.2
python-dotenv==1.0.1
bitsandbytes==0.42.0
mlx-lm==0.16.1
sentencepiece==0.2.0
llama-cpp-python==0.2.83
```

Mac M1 architecture is said to be supported by Pytorch since 2022 so I am expecting torchtune to do so (correct me if I'm wrong). 

If I don't specify a version, torchtune successfully installs but it installs the 0.1.1 version which doesn't have the latest features I want.

**Comment by SalmanMohammadi** [comment]
Hey @Timelessprod. Thanks for checking torchtune out!

We're currently in the process of integrating MPS support in torchtune. Check out #1233 to follow along.

**Comment by Timelessprod** [comment]
Thanks !
