### ISSUE TITLE
Add validation for `model_transform` param in `SFTDataset`

### ISSUE THREAD

**Issue by joecummings** [pytorch/torchtune#1326]
In the docs, we mention that the model_transform is expected to return "tokens" and "mask". 

We should add better validation that these are the returned values and blame the transform. Right now, we just get a key error.

**Comment by andrewldesousa** [comment]
@joecummings hey can you assign this one to me if still available? i can fix this one in the coming days

**Comment by RdoubleA** [comment]
sounds good @andrewldesousa, thanks for taking this up! let us know when you're ready for one of us to look at the changes
