### ISSUE TITLE
Tracker for dataset improvements

### ISSUE THREAD

**Issue by RdoubleA** [pytorch/torchtune#1337]
- Explain what type of dataset each builder is (SFT, CPT, Preference, etc)
- Give a config and code example in each builder for both the default source and customizing it
- Give a config and code example in each base dataset class docstring for custom data (SFT, Text Completion, Preference)
- Possibly add generic builders for SFT, Text Completion, Preference to make it easier to specify custom data from config (this may not be straightforward anymore because of the message transform stuff, but maybe we can use simplified parameters with builders like instruct, chat, etc)
- Add `filter_fn` back to `SFTDataset` (cc @joecummings)
- Add `filter_fn` to `text_completion_dataset` (#1396)
- Update `JSONToMessages` to align with OpenAI API structure (#1373)
- Message validation in SFTDataset (#1391)
- Use merged prompt template in generate recipe (#1392)
- Enable configuring system prompt in generate recipe (#1393)

Other issues: #1369, #1295, #1362

**Comment by SalmanMohammadi** [comment]
I've written some DPO recipe docs where I cover preference datasets a bit. Happy to move it + reference the docstring if you'd prefer.
