### ISSUE TITLE
Reproducing benchmark numbers

### ISSUE THREAD

**Issue by iankur** [pytorch/torchtune#1365]
Hi, I am running Llama-3-8b base model on old open-llm-leaderboard tasks with batch size 1 and add_bos=True. I am getting a score of ~49 for GSM8k whereas open-llm-leaderboard score for meta-llama/llama-3-8b is ~45 on the same task (both 5-shot). Is there any way I can get similar numbers on my runs?

**Comment by felipemello1** [comment]
Hey iankur, I don’t know the answer, but here is a guess: is your model in fp16? If so, maybe try using fp32.

If you are already using the correct tokenizer, then small diferences in the implementation may influence it, like removing extra white spaces or not. Take a look here: https://x.com/danielhanchen/status/1823084024593838344?s=46
