### ISSUE TITLE
custom llm

### ISSUE THREAD

**Issue by den-run-ai** [pytorch/torchtune#1372]
How to add a custom llm?
I don't see any docs to follow this in steps or any discussions in the issues.
For example start with Mistral template and customize for specific model of the same family.
Any help would be appreciated.

**Comment by RdoubleA** [comment]
Hi @den-run-ai, what in particular are you looking to customize? Are you planning to modify the model architecture or the prompt template?

If you're interested in modifying the model and creating your own, take a look at the Mistral model builders (https://github.com/pytorch/torchtune/blob/2f8ed7a34457eaddce59a58e8c37dd51d6ba65f8/torchtune/models/mistral/_model_builders.py#L29) to see how they customize the generic `mistral` constructor (https://github.com/pytorch/torchtune/blob/2f8ed7a34457eaddce59a58e8c37dd51d6ba65f8/torchtune/models/mistral/_component_builders.py#L38) to define the architecture. 

If you'd like to change the prompt template, you can copy the Mistral template (https://github.com/pytorch/torchtune/blob/main/torchtune/models/mistral/_prompt_template.py#L11) and make modifications.
