### ISSUE TITLE
Is Custom Eleuther Eval supported?

### ISSUE THREAD

**Issue by dpalmasan** [pytorch/torchtune#1376]
I would like to use `google/boolq` dataset https://huggingface.co/datasets/google/boolq so I can tune a model and then compare results between the base model and the fine-tuned model. I was already able to tune the model but I would like to run an evaluation like in the following `lm_eval` example: https://github.com/EleutherAI/lm-evaluation-harness/blob/main/examples/lm-eval-overview.ipynb

Is this currently supported? I don't see such a config in the e2e workflow example: https://pytorch.org/torchtune/stable/tutorials/e2e_flow.html

**Comment by joecummings** [comment]
If I understand your question correctly, this should work using the ``include_path`` param. 

See this gist for more information: https://gist.github.com/yasser-sulaiman/91ef64a428e1063064c6e556ec5833bd.

Once you format the BoolQ dataset according to the right EvalHarness params, you should be able to evaluate! LMK if this helps :)

**Comment by dpalmasan** [comment]
Nice! Yes, this solves this question, thanks
