### ISSUE TITLE
Add filter_fn to text_completion_dataset

### ISSUE THREAD

**Issue by RdoubleA** [pytorch/torchtune#1396]
Unstructured text corpuses are often raw and have many empty lines. Adding the ability to apply a filter_fn similar to `SFTDataset` [here](https://github.com/pytorch/torchtune/blob/f9f75bb563ecae371492a9d49da4a9f514c081b3/torchtune/datasets/_sft.py#L102) would be very useful. See #1394 as an example.

**Comment by AnuravModak** [comment]
Heyy, if you are looking for external contribution on this, do let me know ! Will be happy to take this up and try to solve it!

**Comment by joecummings** [comment]
> Heyy, if you are looking for external contribution on this, do let me know ! Will be happy to take this up and try to solve it!

@AnuravModak - We would love to accept a PR from you on this work! Please tag @RdoubleA  and me for review.

**Comment by AnuravModak** [comment]
> hey @AnuravModak, just checking in! let us know if your plans change

Heyy @RdoubleA , sorry for the delay! right now i am working on my first draft, will raise a PR today.

**Comment by AnuravModak** [comment]
Hi @RdoubleA , i have raised a PR: https://github.com/pytorch/torchtune/pull/1429. Please review and provide feedback!
