### ISSUE TITLE
Mighty Nit: Standardize `torch.Tensor` typing

### ISSUE THREAD

**Issue by SalmanMohammadi** [pytorch/torchtune#1420]
Sometimes we typehint `torch.Tensor`, sometimes it's `Tensor`. Wouldn't it be great if it all looked the same?

**Comment by varshinimuthukumar1** [comment]
@SalmanMohammadi Can I work on this?

**Comment by SalmanMohammadi** [comment]
Hey @varshinimuthukumar1! Thanks for asking. Absolutely. Feel free to put up a PR and ping me on it. : )

cc @RdoubleA @ebsmothers @felipemello1 @pbontrager choose your fighter

🚀 = `torch.Tensor`
👀 = `Tensor`

**Comment by pbontrager** [comment]
Why make typing take up more space than it already does?

**Comment by felipemello1** [comment]
to save an extra import :P

**Comment by RdoubleA** [comment]
using `Tensor` requires adding an extra import line `from torch import Tensor`, you already have torch imported in almost all files just stick with it :)

**Comment by felipemello1** [comment]
i think it also bothers me a bit when i see "Tensor". Ok, what type of Tensor? Is it a torch.Tensor? :D

**Comment by varshinimuthukumar1** [comment]
Thanks for assigning this issue to me. I will put up a PR!

**Comment by SalmanMohammadi** [comment]
Not to throw a wrench in the works here but pytorch also uses `Tensor`...

**Comment by felipemello1** [comment]
they use both 
![image](https://github.com/user-attachments/assets/7a83d661-fc82-466f-a7d4-f362fa5f2b79)

But i just dont know if the time spent on it is worth on it haha. Since @varshinimuthukumar1  is willing to contribute, maybe the time would be better spent in other tickets with "good first issue" and "community help wanted"

**Comment by varshinimuthukumar1** [comment]
I took up this issue to get a first-feel of the code base, and contribute further.

If it is not needed, I will drop this issue, and start elsewhere :D

**Comment by felipemello1** [comment]
I think it would be better. The torch.tensor is just cosmetic, but there are plenty of open issues that would have an impact by creating new features or solving small issues that affect users.

Thanks for contributing @varshinimuthukumar1 ! Feel free to share your thoughts and ask questions as you get more familiar with torchtune :)
