### ISSUE TITLE
More explicit compile variables in our recipes

### ISSUE THREAD

**Issue by ebsmothers** [pytorch/torchtune#1426]
Right now we support compiling the model with `compile=True` in our config and set the `self._model_compile` variable in our recipes (e.g. [here](https://github.com/pytorch/torchtune/blob/05aeb71bec637f26a5b14e16638d445c1f7a8deb/recipes/full_finetune_single_device.py#L204)). But in reality there are a couple different places that compile can be applied: FlexAttention, model layers, and finally loss (which also needs special handling depending on vanilla vs chunked CE). We plan to continue to handle these all with a single `compile` config field, but then we should rename `self._model_compile` in the recipes to be clearer about what we're actually compiling.

**Comment by joecummings** [comment]
Done!
