### ISSUE TITLE
See if config.instantiate should always instantiate dict/list as primitive types

### ISSUE THREAD

**Issue by RdoubleA** [pytorch/torchtune#1444]
In some cases arguments passed to `_component_` get instantiated as `ListConfig` or `DictConfig` when really we want the primitive `list` or `dict`. Investigate why this is happening, and if it should always default to instantiating the primitive type.

More context: https://github.com/pytorch/torchtune/pull/1433#issuecomment-2316404063

**Comment by ebsmothers** [comment]
Ya this seems suspicious to me. Like how is this different from what we do with our LoRA configs?
