### ISSUE TITLE
[Qwen2 tokenizer] Ensure ``eos_token`` is not added if ``add_eos=False``

### ISSUE THREAD

**Issue by joecummings** [pytorch/torchtune#1478]
Fix similar to #1477 

Add a test and ensure it passes.

**Comment by krammnic** [comment]
For all this 4 similar issues I can conclude: 
1. For Qwen2 check is similar to Llama3
2. For gemma and mistral - fix will be same: is user do not add eos_token, None should be passed to `tokenize_messages_no_special_tokens` which held condition: if `eos_id is not None else None` satisfied correctly.
3. For Phi probably same check as in Llama while truncating

Final solution:
1. Add required conditions
2. Cover each with unittest(pretty similar to Llama test)

Correct me please if I'm not right in some point and I can open PR.
