### ISSUE TITLE
[Phi3 tokenizer] Ensure ``eos_token`` is not added if ``add_eos=False``

### ISSUE THREAD

**Issue by joecummings** [pytorch/torchtune#1481]
Fix similar to #1477

**Comment by ebeyabraham** [comment]
Hi @joecummings, is anyone working on this issue at the moment? Happy to take this up.

**Comment by joecummings** [comment]
> Hi @joecummings, is anyone working on this issue at the moment? Happy to take this up.

We would love a PR! Please tag me on it and lmk if you have any questions :)
