### ISSUE TITLE
Extremely slow performance with ``utils.generate()``

### ISSUE THREAD

**Issue by lucas-ventura** [pytorch/torchtune#1533]
I'm experiencing extremely slow generation times using the ``InferenceRecipe`` from ``torchtune-0.2.1`` with the LLaMA3.1 model without 
fine-tuning. My workflow involves calling ``recipe.setup()`` and then using ``recipe.generate()`` for every prompt.

For comparison, using the Hugging Face pipeline with the same model (LLaMA3.1), generating 100 samples takes around 14 minutes. However, with ``torchtune``, generating the same 100 samples with identical prompts takes over 17 hours.

Could you help me understand what might be causing this significant slowdown, and is there any way to speed up the generation process with ``torchtune``?

**Comment by SalmanMohammadi** [comment]
Could you share any corresponding HF code? Are you using KV-cacheing with HF?

Models like LLama3.1 have very long context lengths, so it's advised not to use KV-cacheing during decoding with them, as we default to setting the cache up with the maximum sequence length of the model. If this is the case and you're not using KV-cacheing, it could explain the speed difference.

We have an overhaul of our generation + cacheing utilities in the works, which, among other things, allows you to use KV-cacheing with long-context-length models like Llama3.1 by overriding the cache sequence length. Hopefully this should help when it lands in the next week or two.

**Comment by lucas-ventura** [comment]
Thank you for your prompt response!

Here’s the code I’m using with HF:

```python
import transformers
model_id = "meta-llama/Meta-Llama-3.1-8B-Instruct"
pipeline = transformers.pipeline(
    "text-generation",
    model=model_id,
    model_kwargs={"torch_dtype": torch.bfloat16},
    device=device,
)

prompt = pipeline.tokenizer.apply_chat_template(
    prompt, tokenize=False, add_generation_prompt=True
)

terminators = [
    pipeline.tokenizer.eos_token_id,
    pipeline.tokenizer.convert_tokens_to_ids("<|eot_id|>"),
]

outputs = pipeline(
    prompt,
    max_new_tokens=1024,
    eos_token_id=terminators,
    do_sample=True,
    temperature=0.6,
    top_p=0.9,
    pad_token_id=pipeline.tokenizer.eos_token_id,
)

llm_output = outputs[0]["generated_text"][len(prompt):]
```

I’m not entirely sure if this setup uses KV-caching under the hood in HF. Is there anything I can check to verify that?

In the meantime, is there any tweak I can apply with ``Torchtune`` to speed things up before your update is available? Also, can I try the cache implementation in the nightly version beforehand?

Thank you again!

**Comment by SalmanMohammadi** [comment]
I just noticed you're looking at 17 hours in torchtune, sorry, I misread that the first time, that's way too long. Something else may be afoot. Could you share how you're generating in torchtune?

**Comment by lucas-ventura** [comment]
Solved! Setting ``enable_kv_cache=True`` in ``model.setup()`` made it much faster! Thank you so much for your help!!

**Comment by SalmanMohammadi** [comment]
Yeah it makes a huge difference! If you're looking for even more speedups try out compile by moving this line https://github.com/lucas-ventura/torchtune-test/blob/0300272495497255bd20fbe067381ddcf40de37d/inference.py#L171

out of the if-statement for quantized-models only (you could set it under your own flag in the `generate` call in your example. You should see a pretty nice speed bump from there too.
