### ISSUE TITLE
Handle empty prepend/append tags in PromptTemplate

### ISSUE THREAD

**Issue by RdoubleA** [pytorch/torchtune#1565]
We currently assume the prepend/append tags in the prompt template are a string or an empty string. We should add more flexibility here to ignore the tag if its empty or None:

https://github.com/pytorch/torchtune/blob/01619cec87e8904707a06da91ee3f4759341151c/torchtune/data/_prompt_templates.py#L111

**Comment by krammnic** [comment]
Really minor fix. Check for None and change it to empty string should be fine. Will open PR
