### ISSUE TITLE
Installation of `0.2.1` not compatible on mac as the dependency `torchao==0.3.1` can't be fulfilled

### ISSUE THREAD

**Issue by vijaygkd** [pytorch/torchtune#1572]
The installation of `torchtune` version `0.2.1` doesn't successfully complete on Apple mac laptop as `torchao==0.3.1` can't be found for mac platform. As a result the tool can't be used on macbook.

**Comment by vijaygkd** [comment]
![Screenshot 2024-09-12 at 4 55 02 PM](https://github.com/user-attachments/assets/2efe7777-8196-4373-9608-c042bfba7998)

**Comment by felipemello1** [comment]
@joecummings

**Comment by SalmanMohammadi** [comment]
Currently we don't support MPS out of the box, this is something that's been in the works. One of the reasons is that torchao doesn't offer binaries for MPS. You might be able to get around this by installing tochao from source @vijaygkd, before you install torchtune.

**Comment by vijaygkd** [comment]
> I've been informed torchao now has wheels for mac now - @vijaygkd could you give it another try?

Hey I'm still running into the same issue. `torchao 0.3.1` is not available for mac. The other versions are `0.3`, `0.5` as you can see in the screenshot above

**Comment by vijaygkd** [comment]
Let me provide you with a bit more context on the issue. 

Most developers won't be writing code on A100 machines. The developer workflow typically is "write code on local machine (mac / windows)" > "do debugging /  test run on local machine" > "run FT on full dataset on a cloud hosted Nvidia VM (linux / unix)".

The current `torchtune 0.2.1` distribution cannot support the above workflow as I can't install the required `torchao==0.3.1` dependency. 
Minimum requirement : ability to run `tune validate` on test configs and custom dataset templates. 
Ideal scenario : to a test run with a sample dataset locally end-to-end. 

Currently even the minimum requirement can't be fulfilled as `torchao` is pinned to version `0.3.1`. A possible solution would be to unpin the dependency and allow either `0.3` or `0.5`.

I am sure I am missing other complexities here, so please pitch in.

**Comment by SalmanMohammadi** [comment]
Is there a reason you're specifically looking to install torchao 0.3.1- is that coming from trying to `pip install torchtune`? 

If so, try first upgrade torchao `pip install --pre --upgrade torchao --index-url https://download.pytorch.org/whl/nightly/cpu`, and then also make sure you're install torchtune from the latest nightly build
`pip install --pre --upgrade torchtune --index-url https://download.pytorch.org/whl/nightly/cpu`.

**Comment by vijaygkd** [comment]
> Is there a reason you're specifically looking to install torchao 0.3.1- is that coming from trying to `pip install torchtune`?

There is no particular reason. `torch 0.3.1` is pinned for `torchtune 0.2.1`. Any other version would cause a conflict.

**Comment by vijaygkd** [comment]
I see that the dependency was removed as per https://github.com/pytorch/torchtune/pull/1452
I will try the nightly build, hopefully that should resolve it.

**Comment by SalmanMohammadi** [comment]
How did you get on @vijaygkd?

**Comment by ebsmothers** [comment]
@vijaygkd just catching up here. Thanks for sharing the details of your workflow. We have been wanting to properly support Mac for a while now and with torchao unpinned I hope we can at least provide the first stage of support.

Please let me know if you run into issues with the nightly install. We are also planning to release torchtune 0.3.0 in the next couple days so that should unblock you on a stable package.
