### ISSUE TITLE
Fix KV-cacheing + bsz > 1 with eval recipe

### ISSUE THREAD

**Issue by SalmanMohammadi** [pytorch/torchtune#1600]
Currently, the eleuther recipe won't actually work with bsz>1 and KV-cacheing because some batches recieved by `_model_generate` are smaller than the batch size specified. In the code, there's this comment:

```python
        # Setup caches for a given batch size
        # Technically this is not necessary, but it's a good way to ensure that
        # the caches won't error on a different batch size. In addition, caches
        # are not needed for a regular model call, so we just setup here
```
Which also alludes to this, but it makes repeated calls to `setup_caches` to no avail, because there's currently no way to completely tear down caches. `reset_caches` just zeros them out.

cc @joecummings

**Comment by SalmanMohammadi** [comment]
We can probably just set `enable_kv_cache=False` for now if bsz > 1

**Comment by SalmanMohammadi** [comment]
OK one of the kind eleuther folks pointed me to this solution:
```python
        output = evaluate(
            model_eval_wrapper,
            task_dict,
            limit=self._cfg.batch_size,
        )
``` 
which seems to work - my generation test passes (only on the dummy model, mind you). I'll let you try it out.

**Comment by baberabb** [comment]
@SalmanMohammadi Sorry, I jumped the gun. I just realized the PR only works for generation tasks and won't work bug-free for multiple-choice tasks as each sample is expanded times the number of choices (most tasks have an even number but it's not guaranteed). Need to think what the best way would be while remaining back-ward compatible.

**Comment by baberabb** [comment]
@SalmanMohammadi what about this in your eval recipe:

```python
def generate_until(self, requests: List[Instance], **kwargs):
    requests, dummy_len = add_dummy_elem(requests, self.batch_size)
    res = super.generate_until(requests, **kwargs)
    return res[:-dummy_len]
```
