### ISSUE TITLE
PackedDataset cannot handle long sequence whose length is larger than 2*max_seq_len when using split_across_pack=True

### ISSUE THREAD

**Issue by DominicSlw** [pytorch/torchtune#1689]
As the title, it reports a runtime error in the self._pad_pack()
```
f = {"tokens":list(range(121)),"labels":list(range(121))}
x = PackedDataset([f],max_seq_len=60,split_across_pack=True)
for i in x:
    print(i)
```
```
    num_range = torch.arange(
                ^^^^^^^^^^^^^
RuntimeError: upper bound and larger bound inconsistent with step sign
```

**Comment by felipemello1** [comment]
Thanks for raising the issue @DominicSlw !

@RdoubleA, do you mind taking a look when you have a chance?

**Comment by felipemello1** [comment]
Just saw your discord msg. A PR would be much appreciated :)  Let me know if you need any pointers

**Comment by pbontrager** [comment]
What should be the limit here? What if the packed length is 50 and the bs is 2 and the sequence length is 101, the sequence would be longer than the entire packed batch.

**Comment by felipemello1** [comment]
I guess in this case the sequence should be truncated to num_tokens = bsz*max_seq_len, but it sounds like we need to be careful to not introduce new bugs.

**Comment by ebsmothers** [comment]
> What should be the limit here? What if the packed length is 50 and the bs is 2 and the sequence length is 101, the sequence would be longer than the entire packed batch.

Yeah this is OK, right? Like in my mind it's analogous to setting `max_seq_len` when packing is not enabled. In that case we wouldn't throw out long samples, but just truncate them. So the same loss of information is occurring regardless of whether the dataset is packed or not.
