### ISSUE TITLE
fix future warning amp.autocast

### ISSUE THREAD

**Issue by felipemello1** [pytorch/torchtune#1730]
"/home/felipemello/.conda/envs/torchtune-v0.3.1/lib/python3.11/site-packages/torch/utils/checkpoint.py:1399: FutureWarning: `torch.cpu.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cpu', args...)` instead."

when running
```
tune run --nproc_per_node 8 lora_finetune_distributed --config llama3/70B_lora
```

**Comment by joecummings** [comment]
@felipemello1 This seems like a PyTorch Checkpointing issue. Are they planning on fixing it? Or are we finally going to migrate to a different checkpointing API?

**Comment by felipemello1** [comment]
this only happens on stable, doesnt happen on pytorch nightlies

**Comment by joecummings** [comment]
Okay, so I'm guessing the plan is to wait for 2.5 to come out?

**Comment by ebsmothers** [comment]
Since 2.5 becomes stable in about 1.5 weeks I am gonna close this issue, I don't think there's any action required here
