### ISSUE TITLE
v0.4.0 release tracker 

### ISSUE THREAD

**Issue by joecummings** [pytorch/torchtune#1747]
**Estimated release date:** Tuesday, November 5th
**Estimated branch cut date (aka code freeze):** Tuesday, October 29th
**Actual branch cut date:** Thursday, October 31 🎃
Release owner: @joecummings 

### New features:

- [x] #1645
- [x] #1847 (@felipemello1)
- [x] #1820
- [x] #1631 (@lindawangg, @ebsmothers)
- [x] #1726 (@ebsmothers)
- [x] #1837 (@felipemello1)
- [x] #1763
- [x] #1863 (@calvinpelletier)

### Docs

- [x] #1876 
- [x] #1843 (@ebsmothers)
- [x] #1844 (@joecummings)
- [x] #1845 (@RdoubleA)
- [x] #1846 (@felipemello1)
- [x] #1851 (@SalmanMohammadi)
- [x] #1910 (@RdoubleA)
- [x] #1918
- [x] #1916

### QoL improvements:

- [x] #1757 

### Bug fixes:

- [x] #1777 
- [x] #1778 
- [x] #1764 
- [x] Metaformers <> torchtune discrepancies (@pbontrager, @acisseJZhong) 
- [x] #1818 (@joecummings)
- [x] #1842 (@ebsmothers)
- [ ] #1779 (@pbontrager)
- [x] #1874 (@pbontrager)
- [x] #1889 (@felipemello1)
- [x] #1917 (@ebsmothers)

### Deprecations -> Removal

- [x] #1781
- [x] #1839 (@RdoubleA)
- [x] #1841 (@SalmanMohammadi)
- [x] #1849 (@RdoubleA)

### New deprecations

- [x] #1815 
- [x] #1587

**Comment by krammnic** [comment]
@joecummings We actually deprecated lr_schedulers in modules(moved to training)

**Comment by RdoubleA** [comment]
can we also add #1767

**Comment by joecummings** [comment]
> can we also add #1767

Yep! Feel free to update the tracker with this once #1767 has a dedicated owner. (Assign one please)

**Comment by joecummings** [comment]
Completed https://github.com/pytorch/torchtune/releases/tag/v0.4.0
