### ISSUE TITLE
Question on FFT on an Pretrained model llama-3.2-3B 

### ISSUE THREAD

**Issue by Vattikondadheeraj** [pytorch/torchtune#1750]
Hey, I have a small query on FFT on llama-3.2-3B PT model. If I wanna FFT a PT model, is it still better to use messages.InputOutputToMessages format? or should I use a different format?

**Comment by RdoubleA** [comment]
Hey @Vattikondadheeraj, what type of dataset are you trying to fine-tune on? If it's a chat multimodal dataset similar to LLaVA Instruct (https://huggingface.co/datasets/liuhaotian/LLaVA-Instruct-150K), you can use the `multimodal_chat_dataset` builder function directly from the config. If it follows a different format, you may need to create your own dataset builder that puts together the transforms you need (see https://pytorch.org/torchtune/stable/basics/multimodal_datasets.html and https://pytorch.org/torchtune/stable/basics/message_transforms.html)

**Comment by Vattikondadheeraj** [comment]
@RdoubleA , I am trying to do FFT on a coding task. So messages.InputOutputToMessages format should work fine right?

**Comment by RdoubleA** [comment]
Ah sorry, I thought you were trying to fine-tune the Llama 3.2 vision model. For the text model, take a look at `torchtune.datasets.instruct_dataset`, which uses the messages.InputOutputToMessages format. So as long as your coding dataset is structured similarly to https://pytorch.org/torchtune/main/basics/instruct_datasets.html#instruct-dataset-format, then you should be good to go.
