### ISSUE TITLE
drop_last does not work with `ConcatDataset`

### ISSUE THREAD

**Issue by RdoubleA** [pytorch/torchtune#1754]
`drop_last` is expected to be specified with the dataset config object, but this errors out when you use multiple datasets and cfg_dataset becomes a ListConfig: https://github.com/pytorch/torchtune/blob/main/recipes/full_finetune_distributed.py#L511

Possible fixes:
- Always use `drop_last=True`
- Explicitly check for ListConfig, if so just use True

**Comment by joecummings** [comment]
I think the severity of this bug should be upgraded since it blocks any current use of `ConcatDataset` OOTB.
