### ISSUE TITLE
Add filter_fn to all dataset builders

### ISSUE THREAD

**Issue by RdoubleA** [pytorch/torchtune#1768]
This is a common operation for any HF based dataset. All dataset builders should have this exposed, right now only text_completion_dataset does and maybe a couple others.

**Comment by krammnic** [comment]
From generic dataset classes, I assume that it is not added only to PreferenceDataset(It is not required in ConcatDataset and PackDataset, because they are composite). Also, probably should be added to builders API with default value None. Will open PR soon.

**Comment by RdoubleA** [comment]
@krammnic you're on an incredible streak, PR would be much appreciated. Yes, PreferenceDataset + preference_dataset, instruct_dataset, chat_dataset need it from the generic dataset builders. Default value None makes sense to me.

**Comment by krammnic** [comment]
Created a PR to fix this. I also thought that add filter_fn in other builders APIs is good idea either
