### ISSUE TITLE
Make `AlpacaToMessages` public

### ISSUE THREAD

**Issue by RdoubleA** [pytorch/torchtune#1769]
Many datasets still use the Alpaca instruct format, but right now `torchtune.datasets._alpaca.AlpacaToMessages` is only discoverable through a private import and not present in our docs at all. We should make this publicly importable and more visible.

**Comment by krammnic** [comment]
Pretty minor code fix, but if it will be public, some docs should be added. Therefore, I'm not sure how to correctly incorporate AlpacaToMessage in docs(currently there is no info about it as it is internal). I see docstring, but should it be included in API Reference -> datasets.alpaca_dataset? Where you think it should be added?

**Comment by joecummings** [comment]
@krammnic  There are two steps to making this public:

1. Import `AlpacaToMessages` into the `data/__init__.py` file and add it to the `all` variable. This will allow it to be imported without hitting the underscore which denotes a private variable.
2. Add it to the API ref in the docs [here](https://github.com/pytorch/torchtune/blob/main/docs/source/api_ref_data.rst#message-transforms).
