### ISSUE TITLE
Make `split=train` default on all dataset builders

### ISSUE THREAD

**Issue by RdoubleA** [pytorch/torchtune#1770]
This may already be the case for a few builders, but it gets annoying to always have to specify this when 90% of the time I do want the train split. This should be default for all dataset builders.

**Comment by krammnic** [comment]
Isn't it not default only for `multimodal_chat_dataset`, `instruct_dataset` and `chat_dataset` builder? If so and change to all of them is required I can open PR.

**Comment by joecummings** [comment]
@krammnic Yep, those should be the ones! Please tag me and @RdoubleA  on the PR and we'd be happy to review.
