### ISSUE TITLE
Why does Phi3 always ignore the prompt?

### ISSUE THREAD

**Issue by zjost** [pytorch/torchtune#1774]
The `__call__` method of the tokenizer invokes: [`self.tokenize_messages`](https://github.com/pytorch/torchtune/blob/main/torchtune/models/phi3/_tokenizer.py#L265), which has the default arg [`ignore_system_prompts: bool = True`](https://github.com/pytorch/torchtune/blob/main/torchtune/models/phi3/_tokenizer.py#L128).  Is this intended?

To be concrete, I'm trying to instruction fine-tune Phi3 and I have a dataset with input/output columns, but I'd like to prepend a system prompt.  I can make my own tokenizer, just want to verify there's not a good reason for this.

**Comment by RdoubleA** [comment]
I remember there was some issue with system prompts with Phi3 in the past, but I can't find the original discussion, maybe @joecummings has more context. It might've been resolved since then.

**Comment by zjost** [comment]
Thanks!  I did some digging and found the [Huggingface discussion](https://huggingface.co/microsoft/Phi-3-mini-4k-instruct/discussions/51#668323bf065caa5a21a2d1e0) was updated by Microsoft in July.  They have updated the model and now support the system prompt, and that's the [currently recommended way](https://huggingface.co/microsoft/Phi-3-mini-4k-instruct#chat-format).

**Comment by zjost** [comment]
In case anyone's interested, I did a simple experiment to understand the impact of different choices around this question, and put the results [in this thread comment](https://huggingface.co/microsoft/Phi-3-mini-4k-instruct/discussions/51#67096690721603bf006a7aa7)
