### ISSUE TITLE
support for gemma-2 

### ISSUE THREAD

**Issue by almugabo** [pytorch/torchtune#1813]
Could you please add fine-tuning support for gemma-2 ? It has good good multilingual capabilities and is a good candidate for fine-tuning for languages other than English. 
Its different sizes also make it attractive for fine-tuning for different tasks. 
I would gladly help but am not knowledgeable enough 
Thank you

**Comment by krammnic** [comment]
Actually, in inspiration of [one current kaggle competition](https://www.kaggle.com/competitions/gemma-language-tuning) - it is really good idea too add this pretty soon.

**Comment by ebsmothers** [comment]
Thanks @almugabo for creating the issue. I think this will be a bit of effort, quickly jotting down a couple of things I'm aware of that we'd need to support:

- [ ] Logit softcapping in attention layer
- [ ] Logit softcapping in output layer
- [ ] Sliding window attention
- [ ] Expose sliding window attention in configurable set of layers
- [ ] Post layernorm for both attention and FFN (hacky thing to do is just use `attn_scale` and `mlp_scale`)
- [ ] Model builders for 2B, 9B, 27B sizes

For logit softcapping and sliding window attention, I suspect we can use FlexAttention APIs. See [this blog post](https://pytorch.org/blog/flexattention/) where they give explicit examples of each.

**Comment by Optimox** [comment]
Hello, I have started the addition of gemma2, I will create now my PR in WIP mode. I haven't run any test yet but will do soon!

**Comment by Optimox** [comment]
I didn't know about FlexAttention, I will look into it!

**Comment by joecummings** [comment]
ADDED!
