### ISSUE TITLE
Tokenizer tests should be refactored (all models)

### ISSUE THREAD

**Issue by krammnic** [pytorch/torchtune#1823]
Discussed with @joecummings Currently, `expected_tokens` is explicitly given in each test separately, even it is pretty always not unique. With current formatting, it makes tests looks really ugly and not strictly. Maybe we should do fixture or add noqa there?

**Comment by krammnic** [comment]
If everyone agree with such change can open PR

**Comment by felipemello1** [comment]
hey Krammnic, are you in our discord? Can you text me there? FelipeM

**Comment by krammnic** [comment]
> hey Krammnic, are you in our discord? Can you text me there? FelipeM

Sure

**Comment by krammnic** [comment]
> > hey Krammnic, are you in our discord? Can you text me there? FelipeM
> 
> Sure

Somehow haven't found you. My handle is same as here.

**Comment by krammnic** [comment]
@RdoubleA @joecummings My opinion that something like noqa + fixture, will be enough. We actually don't really want to see all values clearly, because if something will fail we will obviously see diff. Will open PR
