### ISSUE TITLE
[RFC] Kaggle Model Hub Integration for Torchtune

### ISSUE THREAD

**Issue by KeijiBranshi** [pytorch/torchtune#1852]
**Authors:** @keijibranshi @rosbo @mrisdal @neshdev [at.bflynn](mailto:bflynn@kaggle.com)

# Summary

This RFC proposes extending torchtune to support loading pre-trained and fine-tuned model weights directly from the [Kaggle Model Hub](https://www.kaggle.com/models). This integration aims to expand the accessibility of models within torchtune and contribute to the adoption of both PyTorch/torchtune and the Kaggle Model Hub by streamlining the experience for Kaggle users.

# Motivation

This proposal aligns with PyTorch's objective of integrating with partner platforms to increase Torchtune adoption ([KR 3.2](https://drive.google.com/file/d/1fkOkX-6JhYKyARqCt4adb4FjtS1vz458/view)). By adding support for Kaggle, we can:

* **Increase Model Accessibility:** Provide Torchtune users with a wider selection of pre-trained models and community-shared fine-tuned weights, fostering a more diverse model ecosystem.

* **Community Engagement:** This integration can foster collaboration between the PyTorch and Kaggle communities, leading to increased contributions and a more diverse model ecosystem.

## Other Potential Benefits

* **Streamline Kaggle Competition Workflow:** Enable seamless torchtune model loading within Kaggle competition notebooks, which have internet access restrictions. This eliminates the need for workarounds currently required to use PyTorch models in competitions.
* **Deeper Kaggle Notebook Integration:** Using kagglehub allows for better integration with Kaggle Notebooks, enabling features like automatic model detection and UI enhancements within the notebook environment.

# Prior Art

Similar functionality for loading models from various hubs exists in other deep learning libraries. Keras, for example, provides a unified mechanism for loading models from both Hugging Face and Kaggle using URI schemes (see the[ Keras documentation](https://keras.io/guides/keras_nlp/upload/#upload-the-model-to-a-model-hub)).

# Proposed Implementation

We propose extending torchtune's model loading mechanism to recognize and handle Kaggle Model Hub URIs. This will involve the following:

1. **URI Scheme Recognition:** Torchtune can be updated to recognize model URIs using the `kaggle://` scheme. While Hugging Face will remain the default source for models, we could also add support for explicit Hugging Face URIs using the `hf://` scheme for increased clarity.

2. **Kaggle Hub Integration:** Leverage the [kagglehub](https://github.com/Kaggle/kagglehub) Python library to handle the download and upload of model weights to and from the Kaggle Model Hub.

Using the above, we would modify torchtune's model loading logic to:

1. Detect the URI scheme (`kaggle://` or `hf://`).
2. Utilize kagglehub for downloading weights from Kaggle when a `kaggle://` URI is provided.
3. Maintain the existing Hugging Face integration for models without a URI scheme or those explicitly using `hf://`.

## Example Usage:

Users will be able to download a model from Kaggle using a command like:

```bash
tune download kaggle://metaresearch/llama-3.2/pyTorch/3b \
--output-dir /tmp/llama-3.2-3b \
--kaggle-username <KAGGLE_USERNAME> \
--kaggle-api-key <KAGGLE_API_KEY>
```

# Considerations

* **Backward Compatibility:** This change should not affect existing functionality with Hugging Face models.

* **Dependencies:** Torchtune will need to add [kagglehub](https://github.com/Kaggle/kagglehub) as a dependency. Would the introduction of fsspec for more general URI scheme handling be a desirable enhancement, even if it adds complexity?

* **`--output-dir` Argument:** Since kagglehub utilizes a default cache folder, should the `--output-dir` argument be optional or required for Kaggle models? What are the preferred behaviors and potential implications of each approach?

* **Documentation:** We are willing to contribute to the torchtune documentation to include instructions and examples for using Kaggle Model Hub URIs. Guidance on the documentation update process and procedures would be greatly appreciated.

* **Testing:** Develop comprehensive tests to ensure the correct functionality of Kaggle model loading and compatibility with existing features.

# Call for Feedback

We’d love feedback from the PyTorch community on this proposal. Please share your thoughts, suggestions, and any potential concerns you may have. 

Happy modeling, 
The Kaggle Team

**Comment by joecummings** [comment]
Thanks for the RFC @KeijiBranshi - we're really excited about providing another source for model integration. I'm still closely considering some of the implementation details, so I'll respond to those individually.

**Comment by joecummings** [comment]
**Weight formats**:

Kaggle supports loading models in checkpointing formats that are able to be loaded into different modeling libraries. These are often differentiated by the names "PyTorch" or "transformers" (Hugging Face). Until now, our only model integration source has been the Hugging Face Hub or from Meta directly, which means that we have guarantees that our models can load checkpoints in the "transformers" format or the Meta Llama format. We make no guarantees about any other checkpoint formats. 

At first glance, what this practically means is that if a user tries to load in e.g. Gemma 2 using the following path: `google/gemma-2-2b-jpn-it/flax`, we should throw an error that "flax" is not supported. Where this gets potentially a little trickier is with respect to the "PyTorch" format. For Llama models, this format designates the aforementioned Meta Llama format that we already support. But for e.g. Gemma models, this is the native format released by Google, which means we would have to write additional logic to convert into our torchtune model format. 

On a longer time scale, I'd like to be able to support loading in checkpoints in both the format they were released in + the transformers format, but we don't have the bandwidth to do that right now. So practically, **we'd want to throw an error if someone tries to load a model in any format other than "transformers" unless the organization is "metaresearch", in which case we would also support "PyTorch".** 

Please let me know if I'm missing some details here or if this is too restrictive.

**Comment by joecummings** [comment]
**URI Scheme Recognition:**

I think I have a slight preference for a UX similar to [llama-stack](https://github.com/meta-llama/llama-stack/blob/main/docs/cli_reference.md#downloading-from-meta) wherein the source is specified as a param e.g.:

```
tune download metaresearch/llama-3.2/pyTorch/3b --source kaggle
```

The reason for this is that the "path" for models on the Hugging Face Hub is very recognizable as the entry point to downloading any of their models e.g. 

```python
AutoModel.from_pretrained("openai/whisper-large-v3-turbo")
```
or
```bash
huggingface-cli download openai/whisper-large-v3-turbo
```

Attaching a URI of "hf" would slightly obfuscate that recognition. In addition, this would reduce the need for more complex URI scheme handling.

Open to thoughts.

**Comment by joecummings** [comment]
**--output-dir Argument:**

We're considering changes to our current download process + checkpointing API that would default to downloading the model to the source's cache as a default. So it should be no problem to make ``--output-dir`` optional.

**Comment by KeijiBranshi** [comment]
Thanks for the thoughtful feedback! We appreciate you taking the time to review our proposal and provide your insights.

**Comment by KeijiBranshi** [comment]
> **Weight formats**:
> 
> Kaggle supports loading models in checkpointing formats that are able to be loaded into different modeling libraries. These are often differentiated by the names "PyTorch" or "transformers" (Hugging Face). Until now, our only model integration source has been the Hugging Face Hub or from Meta directly, which means that we have guarantees that our models can load checkpoints in the "transformers" format or the Meta Llama format. We make no guarantees about any other checkpoint formats.
> 
> At first glance, what this practically means is that if a user tries to load in e.g. Gemma 2 using the following path: `google/gemma-2-2b-jpn-it/flax`, we should throw an error that "flax" is not supported. Where this gets potentially a little trickier is with respect to the "PyTorch" format. For Llama models, this format designates the aforementioned Meta Llama format that we already support. But for e.g. Gemma models, this is the native format released by Google, which means we would have to write additional logic to convert into our torchtune model format.
> 
> On a longer time scale, I'd like to be able to support loading in checkpoints in both the format they were released in + the transformers format, but we don't have the bandwidth to do that right now. So practically, **we'd want to throw an error if someone tries to load a model in any format other than "transformers" unless the organization is "metaresearch", in which case we would also support "PyTorch".**
> 
> Please let me know if I'm missing some details here or if this is too restrictive.

**RE: Weight Formats** https://github.com/pytorch/torchtune/issues/1852#issuecomment-2417624558

Agreed that focusing on valid PyTorch and Transformers formats is a good first step. Filtering out incompatible frameworks (e.g. flax) with string manipulation seems straightforward. But excluding PyTorch downloads to just the [Metaresearch](https://www.kaggle.com/organizations/metaresearch) models might yield an awkward experience. Namely, when a user publishes a torchtune fine-tuned model to Kaggle, they would not be able to download their own model later using torchtune.

Should we instead consider doing some post-download validation? In other words, download the model payload, but have torchtune check that the files are properly formatted before proceeding? 

Open to discussing these options and finding the best approach that balances initial simplicity with long-term flexibility.

**Comment by KeijiBranshi** [comment]
> **URI Scheme Recognition:**
> 
> I think I have a slight preference for a UX similar to [llama-stack](https://github.com/meta-llama/llama-stack/blob/main/docs/cli_reference.md#downloading-from-meta) wherein the source is specified as a param e.g.:
> 
> ```
> tune download metaresearch/llama-3.2/pyTorch/3b --source kaggle
> ```
> 
> The reason for this is that the "path" for models on the Hugging Face Hub is very recognizable as the entry point to downloading any of their models e.g.
> 
> ```python
> AutoModel.from_pretrained("openai/whisper-large-v3-turbo")
> ```
> 
> or
> 
> ```shell
> huggingface-cli download openai/whisper-large-v3-turbo
> ```
> 
> Attaching a URI of "hf" would slightly obfuscate that recognition. In addition, without a prefix, there would be no need for more complex URI scheme handling.
> 
> Open to thoughts.

**RE: URI Scheme Recognition** https://github.com/pytorch/torchtune/issues/1852#issuecomment-2417677159

We're happy to defer to your expertise on the use of the --source parameter, especially if it helps make the UX more consistent across similar libraries. 

FWIW, HuggingFace supports the hf:// scheme in some of its own tooling (see [documentation](https://huggingface.co/docs/huggingface_hub/en/guides/hf_file_system#integrations)). But I understand that it’s not a universal concept for model URIs.

**Comment by KeijiBranshi** [comment]
> **--output-dir Argument:**
> 
> We're considering changes to our current download process + checkpointing API that would default to downloading the model to the source's cache as a default. So it should be no problem to make `--output-dir` optional.

**RE: --output-dir Argument** https://github.com/pytorch/torchtune/issues/1852#issuecomment-2417682770

Thanks for sharing those considerations around --output-dir. Currently, kagglehub doesn’t allow users to change the download directory, but we have some related requests on our side to support it.

**Comment by joecummings** [comment]
> **RE: Weight Formats** [#1852 (comment)](https://github.com/pytorch/torchtune/issues/1852#issuecomment-2417624558)
> 
> Agreed that focusing on valid PyTorch and Transformers formats is a good first step. Filtering out incompatible frameworks (e.g. flax) with string manipulation seems straightforward. But excluding PyTorch downloads to just the [Metaresearch](https://www.kaggle.com/organizations/metaresearch) models might yield an awkward experience. Namely, when a user publishes a torchtune fine-tuned model to Kaggle, they would not be able to download their own model later using torchtune.
> 
> Should we instead consider doing some post-download validation? In other words, download the model payload, but have torchtune check that the files are properly formatted before proceeding?
> 
> Open to discussing these options and finding the best approach that balances initial simplicity with long-term flexibility.

Ahh, this is a great consideration. Post-download validation will be fine.

**Comment by joecummings** [comment]
> **RE: --output-dir Argument** [#1852 (comment)](https://github.com/pytorch/torchtune/issues/1852#issuecomment-2417682770)
> 
> Thanks for sharing those considerations around --output-dir. Currently, kagglehub doesn’t allow users to change the download directory, but we have some related requests on our side to support it.

I think it would be a slightly more consistent UX is torchtune users could specify a custom output directory for either Kaggle or the Hugging Face Hub so we'll add our voice to the other related requests :)

But I don't view this as a blocker to this integration.

**Comment by KeijiBranshi** [comment]
Thanks again for the helpful feedback! We're excited to move forward with this integration.

To confirm our understanding of the implementation:

* **Model Loading:** We'll extend torchtune's model loading mechanism to support Kaggle Model Hub URIs using the `--source` CLI argument. For example, the model at https://www.kaggle.com/models/google/gemma/pyTorch/7b should be downloaded with torchtune using the following command:
    ```
    tune download --source kaggle google/gemma/pyTorch/7b
    ```
* **Weight Format Handling:** We'll implement post-download validation to ensure compatibility with torchtune's supported formats.
* **--output-dir Argument:** We'll look into prioritizing custom output directories on the kagglehub side before the torchtune integration, but the timeline for that is TBD.

Could you provide clarification or official documentation on how to validate that the PyTorch weights are provided in the Meta Llama format?

**Comment by KeijiBranshi** [comment]
**Implementation Starting Point:**

It seems like the downloading logic is mostly scoped to the download.py module:

https://github.com/pytorch/torchtune/blob/5252befd963b8e3c25605e7843b62b3003533de7/torchtune/_cli/download.py#L19-L20

Can you confirm if there are any other modules or areas of the codebase that we should be aware of when implementing this feature?

**Comment by KeijiBranshi** [comment]
**Contribution Process:**

We've reviewed [CONTRIBUTING.md](https://github.com/pytorch/torchtune/blob/main/CONTRIBUTING.md). Are there any formal processes or specific requirements beyond what's detailed in that document that we should follow for this feature?

**Comment by KeijiBranshi** [comment]
We appreciate your guidance and look forward to working on this integration! 🙂

**Comment by joecummings** [comment]
> * **Model Loading:** We'll extend torchtune's model loading mechanism to support Kaggle Model Hub URIs using the `--source` CLI argument. For example, the model at [kaggle.com/models/google/gemma/pyTorch/7b](https://www.kaggle.com/models/google/gemma/pyTorch/7b) should be downloaded with torchtune using the following command:
>   ```
>   tune download google/gemma/pyTorch/7b --source kaggle
>   ```

Yep, this looks great!

> * **Weight Format Handling:** We'll implement post-download validation to ensure compatibility with torchtune's supported formats. If available, can you provide any guidance or official documentation on that?

I've thought more about this and I think it requires more of a reworking of our checkpointer, which I'm in the middle of scoping out. For now, I would love that if a model is downloaded from a domain *other* than meta in a PyTorch format, we log a warning that the model format *may* not be supported OOTB in torchtune. Less of a headache for you folks :)

> * **--output-dir Argument:** We'll look into prioritizing custom output directories on the `kagglehub` side before the torchtune integration, but the timeline for that is TBD (but I suppose this could be implemented at the `torchtune` layer with a simple [`shutil.move`](https://docs.python.org/3/library/shutil.html#shutil.move) operation 🤔)

We would love if you could prioritize this work, but moving the files on the backend works well as a stopgap!

**Comment by joecummings** [comment]
> **Contribution Process:**
> 
> We've reviewed [CONTRIBUTING.md](https://github.com/pytorch/torchtune/blob/main/CONTRIBUTING.md?rgh-link-date=2024-10-29T04%3A04%3A36Z). Are there any formal processes or specific requirements that we should follow beyond what's detailed in that doc?

This should have everything you need to get started, but don't hesitate to reach out to me here or [on Discord](https://discord.gg/4Xsdn8Rr9Q)! Super excited for our users to be able to work with the Kaggle Hub soon :)

**Comment by KeijiBranshi** [comment]
howdy. thanks again for your feedback!

I've started adding tests on my local branch and have a quick question. The tests all point to gated models (ie `meta-llama/Llama-2-7b`). How is authentication handled or stubbed in the success case here?
 https://github.com/pytorch/torchtune/blob/eab21f07065574d883b3ec7620a55f1d92f67c8a/tests/torchtune/_cli/test_download.py#L60-L67

Since Kaggle uses it's own tokens for gated access, should I be concerned with how your cicd environment will handle this?

Thanks!

**Comment by joecummings** [comment]
> howdy. thanks again for your feedback!
> 
> I've started adding tests on my local branch and have a quick question. The tests all point to gated models (ie `meta-llama/Llama-2-7b`). How is authentication handled or stubbed in the success case here?
> 
> https://github.com/pytorch/torchtune/blob/eab21f07065574d883b3ec7620a55f1d92f67c8a/tests/torchtune/_cli/test_download.py#L60-L67
> 
> Since Kaggle uses it's own tokens for gated access, should I be concerned with how your cicd environment will handle this?
> 
> Thanks!

Great question and awesome to see the progress so far!

We mock out all actual API calls for the unit tests as shown [here](https://github.com/pytorch/torchtune/blob/eab21f07065574d883b3ec7620a55f1d92f67c8a/tests/torchtune/_cli/test_download.py#L18). It's possibly a little convoluted but every time the `snapshot_download` is called, it iterates over errors returned. Something similar would be good for Kaggle for the unit tests.

It's too difficult to rely on a external API for a unit test that will be called again and again locally and in our CI. The test would easily become flaky and in the success case, we would end up downloading a new model every time. 

In the actual PR, a screenshot of the successful command to download is sufficient as an "integration" test.

**Comment by KeijiBranshi** [comment]
> > howdy. thanks again for your feedback!
> > I've started adding tests on my local branch and have a quick question. The tests all point to gated models (ie `meta-llama/Llama-2-7b`). How is authentication handled or stubbed in the success case here?
> > https://github.com/pytorch/torchtune/blob/eab21f07065574d883b3ec7620a55f1d92f67c8a/tests/torchtune/_cli/test_download.py#L60-L67
> > 
> > Since Kaggle uses it's own tokens for gated access, should I be concerned with how your cicd environment will handle this?
> > Thanks!
> 
> Great question and awesome to see the progress so far!
> 
> We mock out all actual API calls for the unit tests as shown [here](https://github.com/pytorch/torchtune/blob/eab21f07065574d883b3ec7620a55f1d92f67c8a/tests/torchtune/_cli/test_download.py#L18). It's possibly a little convoluted but every time the `snapshot_download` is called, it iterates over errors returned. Something similar would be good for Kaggle for the unit tests.
> 
> It's too difficult to rely on a external API for a unit test that will be called again and again locally and in our CI. The test would easily become flaky and in the success case, we would end up downloading a new model every time.
> 
> In the actual PR, a screenshot of the successful command to download is sufficient as an "integration" test.

Thanks again @joecummings 🙂. I think I understand the `pytest` fixture now. I was initially confused about how `tmpdir` worked, but realized it's set by `pytest` behind the scenes (please correct me if i'm mistaken): https://github.com/pytorch/torchtune/blob/24d3579cb726847603aeb78b7c7d7ffc5d7d96c2/tests/torchtune/_cli/test_download.py#L24

**Next question:** I think it'll take some effort to fully align `--output-dir` behavior between `huggingface_hub` and `kagglehub`. For now, I've added a warning when it's used with `--source kaggle`: https://github.com/KeijiBranshi/torchtune/blob/2a456d5fcddfe87f95e1e92131c6bd20f3dcb21e/torchtune/_cli/download.py#L213-L214

Similarly, `--ignore-patterns` isn't supported in kagglehub, so I'm wondering if a warning message is also needed there. More generally, what's your preferred way to document/log the differences in torchtune functionality between huggingface and kaggle?

**Comment by KeijiBranshi** [comment]
Hi @joecummings. Sorry, was pulled away from this last week. Just put up the official PR into torchtune:main

https://github.com/pytorch/torchtune/pull/2002

Let me know about any next steps! Thank you 🙂
