### ISSUE TITLE
import guard for TorchAO not working in fbcode

### ISSUE THREAD

**Issue by HDCharles** [pytorch/torchtune#1855]
https://github.com/pytorch/torchtune/blob/7d29c21149ace4be9fdc2709a03c0a21ba191010/torchtune/utils/_import_guard.py#L20C1-L29C2

_USE_NEW_TENSOR_CORE_TILED_LAYOUT_API = _is_fbcode() or (
    not _is_fbcode()
    and (
        ("dev" not in torchao_version and torchao_version >= "0.6.0")
        or (
            "dev" in torchao_version
            and _nightly_version_ge(torchao_version, "2024-10-10")
        )
    )
    
    the _is_fbcode() part needs to be removed so this can be updated in fbcode. Its preventing us from landing our diff train.

**Comment by HDCharles** [comment]
@ebsmothers can you take a look at this, i'm going to put a PR up to handle BC briefly so we can move forward with our diff train but i don't think this should be gated on fbcode, just torchao version.

**Comment by ebsmothers** [comment]
@HDCharles this is the version I had added initially. The current version was added by @jerryzh168 in #1834, maybe the two of you can iron this out?

**Comment by ebsmothers** [comment]
Closing this issue since I haven't heard back

**Comment by jerryzh168** [comment]
sorry just saw this, yeah we can close this one
