### ISSUE TITLE
ForwardKLWithChunkedOutputLoss should be averaged over total_non_pad_tokens

### ISSUE THREAD

**Issue by moussaKam** [pytorch/torchtune#1865]
Hi there, 

Currently the loss ForwardKLWithChunkedOutputLoss  is averaged over the chunks which I think is not the right way to do it since there are chunks that contains only pad tokens. [line](https://github.com/pytorch/torchtune/blob/f8073ed24e8e82e74ac923a8134cd66cd6067ad5/torchtune/modules/loss/kd_losses.py#L132C1-L132C55)

I think the right way to do it is to average over the total non pad tokens. I did the fix [here](https://github.com/moussaKam/torchtune/tree/kd_loss_avg_tokens) but couldn't open a pull request because my commit didn't pass the test since the loss did not match with the expected loss.

**Comment by moussaKam** [comment]
Ok I will run some experiments when I have some time a get back to you

**Comment by joecummings** [comment]
Closed by #1885
