### ISSUE TITLE
Question about custom  Fine-tuning

### ISSUE THREAD

**Issue by sorobedio** [pytorch/torchtune#1927]
Hello, I would like to instruction fine-tune the Llama 3.2-1B-instruct  model on a custom dataset using a template similar to Alpaca's r llama template if not possible . However, I would like to specify a set of layers to be fully fine-tuned then later lora tune too. One example is for example. randomly selected of 8 Dense layers regardless their individual position

Could you guide me on how to achieve this?

**Comment by sorobedio** [comment]
Thank you for the response!

I had thought that by setting `requires_grad=True` for the layer I want to fine-tune and `requires_grad=False` for the others, then training the model would update only the weights with `requires_grad=True`. I expected this to solve my problem. hut you said I will not work. so I am confused on that point

**Comment by ebsmothers** [comment]
@sorobedio I think your understanding is correct. Option (1) suggested by @felipemello1 should be the way to go, just set the requires_grad field manually. I think the main question is how often you want to switch between training a subset of the layers and training with LoRA. Felipe’s concern may have been that you want to switch the set of trainable params every step or something, in which case you’d need to ensure the optimizer is aware of the full set of trainable params up front.

**Comment by sorobedio** [comment]
aha sorry for the confusion. I want to train two separate models. one Lora fine-tuned some specific layers instead of all as LoRA approaches often do. and the other approach is to fully fine-tune the same specific layers without lora.
Thank you
