### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by sorobedio** [pytorch/torchtune#1951]
could you include an easier way to do spectrum target fine-tuning> for both instruction and others

"https://github.com/cognitivecomputations/spectrum"
thank you

**Comment by felipemello1** [comment]
hey @sorobedio , thanks for suggesting it!! Spectrum is interesting, but we currently don't have bandwidth to implement it. If you feel like contributing, please let us know. Usually the best way is to create an issue or PR with a draft/proposal, so we can review and align, and then the actual PR with the implementation.

**Comment by sorobedio** [comment]
ok i will try to do something in this regard
thank you.
