### ISSUE TITLE
AdamW still not working in Distributed full finetuning settings

### ISSUE THREAD

**Issue by Vattikondadheeraj** [pytorch/torchtune#1955]
Hey, 

I was again testing the distributed full finetuning recipe and I found out that the AdamW is still not working. Currently I again switched back to Adam optimizer. I have attached the link of my previous issue below. Thank you for your time.

https://github.com/pytorch/torchtune/issues/1710

**Comment by felipemello1** [comment]
closing this in favor of 1710. Will reply there
