### ISSUE TITLE
ModuleNotFoundError: No module named 'torchtune.utils.FullModelHFCheckpointer'

### ISSUE THREAD

**Issue by jinz2014** [pytorch/torchtune#1990]
The command to install the tools:

pip3 install --pre --upgrade torch torchvision torchaudio torchao --index-url https://download.pytorch.org/whl/nightly/rocm6.2

Running torch tune shows the following error.

ModuleNotFoundError: No module named 'torchtune.utils.FullModelHFCheckpointer'

**Comment by tginart** [comment]
The installation is finicky. I had to mess around with for a while with a fresh env to make it work. Good luck.

**Comment by RdoubleA** [comment]
What is your version of torchtune? Since you've installed the rocm version of pytorch you may need to do something similar for torchtune:
`pip install --pre torchtune --extra-index-url https://download.pytorch.org/whl/nightly/rocm6.2 --no-cache-dir`

**Comment by jinz2014** [comment]
Thank you for your comments and suggestions.

pip uninstall  torchtune
Found existing installation: torchtune 0.3.1
Uninstalling torchtune-0.3.1:

**Comment by jinz2014** [comment]
pip install --pre torchtune --extra-index-url https://download.pytorch.org/whl/nightly/rocm6.2 --no-cache-dir

Successfully installed torchtune-0.4.0.dev20241112+rocm6.2

**Comment by jinz2014** [comment]
I created a fresh env, but the error is still there.

**Comment by SalmanMohammadi** [comment]
Hey @jinz2014 - could you share the config you're using? `checkpointer._component_` in your config should be `torchtune.training.FullModelHFCheckpointer`.

**Comment by jinz2014** [comment]
@SalmanMohammadi   Thanks for the solution.
