### ISSUE TITLE
Integrate Lora fine-tuned model with HF

### ISSUE THREAD

**Issue by GLorenzo679** [pytorch/torchtune#2025]
Hello, I'm having some issues when using a Lora fine-tuned model with HuggingFace `from_pretrained()`.
I saw some discussions in the issues, and this one #933 caught my attention.
It's suggested to do this in order to load the fine-tuned model: 

``` python
from transformers import AutoModelForCausalLM
from peft import PeftModel

# hub ID of the base model from the above fine-tune
model_id = "meta-llama/Llama-2-7b-hf" 

# output_dir from tune command
checkpoint_dir = "/my/output/dir" 

model = AutoModelForCausalLM.from_pretrained(model_id)
peft_model = PeftModel.from_pretrained(model, checkpoint_dir)
```
Isn't it possible to load the model (`AutoModelForCausalLM.from_pretrained(model_id)`) from a previously downloaded model (the one that you get with tune download), instead of having to download it again from HF?

If I try to load the previously downloaded model I get this error:

```
venv/lib/python3.12/site-packages/transformers/models/auto/auto_factory.py", line 514, in from_pretrained
    pretrained_model_name_or_path = adapter_config["base_model_name_or_path"]
                                    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'base_model_name_or_path' 
```
Looking at the code that generates the error, it seems like the transformers library is checking if peft the package is installed. If it is so, it looks for the adapter_config.json file (in my case the one generated with tune run) which is missing the `base_model_name_or_path` field.

**Comment by GLorenzo679** [comment]
Thanks for the fast reply.
Your fix solved the problem. I got another error though.

```
venv/lib/python3.12/site-packages/transformers/modeling_utils.py", line 555, in load_state_dict
    with safe_open(checkpoint_file, framework="pt") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: No such file or directory: "models/codeLlama-7B/model-00001-of-00002.safetensors"
```

I solved this by deleting the `model.safetensors.index.json` file in the model folder.

**Comment by GLorenzo679** [comment]
I have an update on this issue.
It seems that `AutoModelForCausalLM.from_pretrained` is loading the base model (the safetensors files) and not the base+adapter model generated with `torch run`.
Is there a way to use a fine-tuned model generated with `torch run` in huggingface?
I found on the documentation ([https://pytorch.org/torchtune/stable/tutorials/e2e_flow.html#using-torchtune-checkpoints-with-other-libraries](https://pytorch.org/torchtune/stable/tutorials/e2e_flow.html#using-torchtune-checkpoints-with-other-libraries) that it's recommended to create a new state_dict with the corresponding index file.
This process is a bit tedious though, isn't there a more straightforward way?

I leave attached my model folder:
![model](https://github.com/user-attachments/assets/2714af48-8d75-4a7d-b38d-ed5281ffa573)

**Comment by felipemello1** [comment]
related: https://github.com/pytorch/torchtune/issues/2048

**Comment by felipemello1** [comment]
> "This process is a bit tedious though" 

@GLorenzo679, i agree 100%. I am working on fixing it . Meanwhile, please do it manually and delete from the folder the other files. This should unblock you.

**Comment by GLorenzo679** [comment]
Thanks for pointing out that related issue!
I locally changed my `save_checkpoint` method as described in #2048 and now I can properly load the fine-tuned model.
The `from_pretrained()` loads safetensors as the default behaviour.
To load the `.bin` files I just needed to add the `use_safetensors=False` argument in the `from_pretrained()` method.
With the other fix suggested by @ebsmothers I can now say that it's possible to load LoRA fine-tuned models in HF.

**Comment by felipemello1** [comment]
hey folks, PR is merged: https://github.com/pytorch/torchtune/pull/2074

Now it should be much easier to use vllm/huggingface. Instructions are in the readme. 

We will update the docs soon. Let us know if you find any issues and thanks for your patience :).

**Comment by joecummings** [comment]
> Instructions are in the readme.

@felipemello1 Where in the README are the instructions? I don't see them.

**Comment by felipemello1** [comment]
Sorry, I meant to say that they are in the pr description -.-
