### ISSUE TITLE
tune validate error Unsupported interpolation type env

### ISSUE THREAD

**Issue by fabiogeraci** [pytorch/torchtune#2097]
running `tune validate config_files/8B_full_single_device.yaml` reports the following error, but it actually works using `tune run`

>   File "/software/isg/users/fg12/envs/virtualenvs/mlflow-torchtune-31tjdLhK-py3.11/lib/python3.11/site-packages/omegaconf/grammar_visitor.py", line 389, in _unescape
>     text = str(self.visitInterpolation(node))
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/software/isg/users/fg12/envs/virtualenvs/mlflow-torchtune-31tjdLhK-py3.11/lib/python3.11/site-packages/omegaconf/grammar_visitor.py", line 125, in visitInterpolation
>     return self.visit(ctx.getChild(0))
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/software/isg/users/fg12/envs/virtualenvs/mlflow-torchtune-31tjdLhK-py3.11/lib/python3.11/site-packages/antlr4/tree/Tree.py", line 34, in visit
>     return tree.accept(self)
>            ^^^^^^^^^^^^^^^^^
>   File "/software/isg/users/fg12/envs/virtualenvs/mlflow-torchtune-31tjdLhK-py3.11/lib/python3.11/site-packages/omegaconf/grammar/gen/OmegaConfGrammarParser.py", line 1041, in accept
>     return visitor.visitInterpolationResolver(self)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/software/isg/users/fg12/envs/virtualenvs/mlflow-torchtune-31tjdLhK-py3.11/lib/python3.11/site-packages/omegaconf/grammar_visitor.py", line 179, in visitInterpolationResolver
>     return self.resolver_interpolation_callback(
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/software/isg/users/fg12/envs/virtualenvs/mlflow-torchtune-31tjdLhK-py3.11/lib/python3.11/site-packages/omegaconf/base.py", line 750, in resolver_interpolation_callback
>     return self._evaluate_custom_resolver(
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/software/isg/users/fg12/envs/virtualenvs/mlflow-torchtune-31tjdLhK-py3.11/lib/python3.11/site-packages/omegaconf/base.py", line 702, in _evaluate_custom_resolver
>     raise UnsupportedInterpolationType(
> omegaconf.errors.UnsupportedInterpolationType: Unsupported interpolation type env
>     full_key: output_dir
>     object_type=dict

**Comment by calvinpelletier** [comment]
Is this one of the example configs? If so, which one? If not, could you post the full config?

**Comment by fabiogeraci** [comment]
[Llama3.1 8B single-device](https://github.com/pytorch/torchtune/blob/main/recipes/configs/llama3_1/8B_full_single_device.yaml)

**Comment by calvinpelletier** [comment]
I'm running `tune validate recipes/configs/llama3_1/8B_full_single_device.yaml` and not getting any errors. Are you on omegaconf version 2.3.0 and the latest torchtune?

From the error you posted originally, it looks like the `output_dir` field is the wrong type (it should be a string).

**Comment by fabiogeraci** [comment]
I run the test and it did not work. let me expplain, I run torchtune using a cluster job, where I set up path to dataset, output_dir and so on. I thought that since I was setting up the env in the launch_script and runnning tune validate directly from the prompt without using the script would lead to the error, but it is not the case. I attached the config file and the full error trace. l
[8B_full_single_device.txt](https://github.com/user-attachments/files/17989737/8B_full_single_device.txt)
[full_trace.txt](https://github.com/user-attachments/files/17989763/full_trace.txt)

**Comment by fabiogeraci** [comment]
I traced back my steps, and in order to get `${env:ARTIFACT_LOCATION}` to work i added the following

```
from omegaconf import **OmegaConf**, DictConfig, ListConfig
# Register the resolver before parsing the config
OmegaConf.register_new_resolver("env", lambda x: os.environ.get(x, f"${{{x}}} not found"))
```

**Comment by fabiogeraci** [comment]
I guess oc.env would eliminate the need of the register line?

**Comment by fabiogeraci** [comment]
thanks that works, i am new to OmegaConf. just in case no need of

OmegaConf.register_new_resolver("env", lambda x: os.environ.get(x, f"${{{x}}} not found"))
