### ISSUE TITLE
TypeError: unsupported operand type(s) for /: 'str' and 'str' in torchtune/data/_messages.py 

### ISSUE THREAD

**Issue by AaronDinesh** [pytorch/torchtune#2109]
Hello, I am trying to run torchtune on a vqa multimodal dataset. When trying to run the torchtune script I ran into this error:
"
File "/home/usr/ml-project-2-a-3/python_venv/lib64/python3.9/site-packages/torchtune/data/_messages.py", line 210, in __call__
    image_path = self.image_dir / image_path
TypeError: unsupported operand type(s) for /: 'str' and 'str'
"

Upon reviewing the code I think line 210 is meant to be
"
    image_path = f"{self.image_dir}/{image_path}"
"
and not:
"
     image_path = self.image_dir / image_path
"

**Comment by joecummings** [comment]
Thanks for reporting @AaronDinesh - just curious, are you trying to run this on a custom dataset or just OOTB?

**Comment by joecummings** [comment]
No need! Apologies for the issue - it should be fixed now if you want to use from source. Otherwise, you can install the nightly build in ~ 12 hours when that job runs.
