### ISSUE TITLE
Make distributed available outside of torchtune.training

### ISSUE THREAD

**Issue by andrewkho** [pytorch/torchtune#2151]
Modules in torchtune.data can't import get_world_size_and_rank from torchtune.training._distributed because of circular imports. Making this available in torchtune._distributed instead would fix this issue
https://github.com/pytorch/torchtune/pull/1929#discussion_r1879199687_

**Comment by joecummings** [comment]
Let me just go ahead and do this now

**Comment by andrewkho** [comment]
Thank you @joecummings !
