### ISSUE TITLE
Grad Clip in FSDP 

### ISSUE THREAD

**Issue by ishitamed19** [pytorch/torchtune#2169]
Hi, 
I have a query. Why do you use torch's own _clip_grad_norm function here? https://github.com/pytorch/torchtune/blob/main/recipes/full_finetune_distributed.py#L781-L784

```
                        if self._clip_grad_norm is not None:
                            grad_norm = torch.nn.utils.clip_grad_norm_(
                                self._model.parameters(),
                                max_norm=float(self._clip_grad_norm),
                            )
```

Since it's a FSDP wrapped model, shouldn't we be calling FSDP's own clip_grad func()? i.e.:
```
                       if self._clip_grad_norm is not None:
                            grad_norm = self.model.clip_grad_norm_(
                                max_norm=float(self._clip_grad_norm),
                            )
```

**Comment by mirceamironenco** [comment]
I believe this is done since the models are wrapped using the FSDP2 `fully_shard` API rather than FSDP (`FullyShardedDataParallel`), the former being compatible (as e.g. DDP) with the default `clip_grad_norm_` ([excluding the case of pipeline parallelism](https://github.com/pytorch/torchtitan/blob/main/torchtitan/utils.py#L348)).

**Comment by ebsmothers** [comment]
@ishitamed19 thanks for creating the issue. It's as @mirceamironenco said, FSDP2-wrapped models will utilize DTensors which have their own implementation of common ops (e.g. [_NormPartial](https://github.com/pytorch/pytorch/blob/64d44a39a10a3e4b7abc85ffadd831ace3227460/torch/distributed/tensor/_ops/_math_ops.py#L56), which is used in `nn.utils.clip_grad_norm_`). You can also see torchtitan's docs on FSDP2 [here](https://github.com/pytorch/torchtitan/blob/62743776a80afa14975026060a96cf74e40550b8/docs/fsdp.md#fsdp1--fsdp2-api-differences): they explicitly mention that with FSDP2 you should use `nn.utils.clip_grad_norm_`

**Comment by ishitamed19** [comment]
@mirceamironenco @ebsmothers Oh I see. Thanks for the quick response! :)
