### ISSUE TITLE
--ignore-patterns doesn't work in tune download

### ISSUE THREAD

**Issue by enqidu** [pytorch/torchtune#2205]
for example

`tune download meta-llama/Meta-Llama-3.1-70B-Instruct --output-dir tmp/Meta-Llama-3.1-70B-instruct  --ignore-patterns ".pth"`

still downloads pth files

**Comment by joecummings** [comment]
Our `--ignore-patterns` argument passes through to the Hugging Face Hub `snapshot_download()` command. You can see here how they use it to filter out files: https://huggingface.co/docs/huggingface_hub/en/guides/download#filter-files-to-download.

I think you need to change you command to the following:
```bash
tune download meta-llama/Meta-Llama-3.1-70B-Instruct --output-dir tmp/Meta-Llama-3.1-70B-instruct  --ignore-patterns "*.pth"
```

**Comment by enqidu** [comment]
Very well, that's the probably the reason, thanks!
