### ISSUE TITLE
Periodic testing of external APIs

### ISSUE THREAD

**Issue by joecummings** [pytorch/torchtune#269]
We are adding several dependencies in our codebase for external services like huggingface_hub, wandb, etc. 

As mentioned by @laurencer , it's important for us to keep an eye on these services to ensure they are up and running properly. Filing this issue for us to come back and consider adding in a form of testing that periodicially pings these APIs to ensure a 200 OK response.

**Comment by kartikayk** [comment]
Tracking this in #691 instead.
