### ISSUE TITLE
[LoRA CI] Test resume from checkpoint functionality

### ISSUE THREAD

**Issue by rohan-varma** [pytorch/torchtune#377]
- Crucial to test this as resuming from LoRA requires 2 checkpoints (base model and adapters) to be loaded in correctly.

**Comment by ebsmothers** [comment]
Closing as we have this [here](https://github.com/pytorch/torchtune/blob/8fa0bbbae09ececb4c362277323d14db81296c03/tests/recipes/test_lora_finetune_single_device.py#L130) for the single device recipe and [here](https://github.com/pytorch/torchtune/blob/8fa0bbbae09ececb4c362277323d14db81296c03/tests/recipes/test_lora_finetune_distributed.py#L89) for the distributed recipe.
