### ISSUE TITLE
[Discussion] "tune download" behavior is unintuitive 

### ISSUE THREAD

**Issue by kartikayk** [pytorch/torchtune#411]
As I walked through ```tune download``` as a user, I found the behavior unintuitive. Concretely:

- **Name**. ```download``` should be renamed to ```hf_download```. That's what this command does and without any information, I get the impression that I can use this to download a model from any source.

- **Restrictions**. ```download``` currently restricts my choices to what is defined in ```_SUPPORTED_MODEL_REPO_IDS```. This seems arbitrarily restrictive since I could download a model, write my own conversion script and use TorchTune to finetune the model. This was the use case I had in mind and i ended up having to modify code to do this. The behavior I would expect in this case is, let the user download the model they want but raise a warning if the model is not supported OOTB. Anyways ```convert-checkpoint``` will raise an error, so I'm not too concerned about the user shooting themselves in the foot by fine-tuning a model we don't support.

**Comment by joecummings** [comment]
@kartikayk  Can this be closed?

**Comment by kartikayk** [comment]
@joecummings yup sounds good. The last bit of clean up with download would be to just log the stuff that we "ignore". I realized this as I was overriding it this weekend. It might not be immediately obvious to folks unless they look at ```tune download --help```. So a simple log of what is being ignored might be good. Otherwise, happy to close this. Thanks so much for the refactor!
