### ISSUE TITLE
[Backlog] Consolidated tracker for potential feature requests

### ISSUE THREAD

**Issue by kartikayk** [pytorch/torchtune#414]
Creating a single tracker for potential feature requests which are currently not on the roadmap. This will help with tracking and prioritization, and remove issues with no context and no plan of action.

## Post-training integrations
- Gradio script for Fine-tuned models [#67]

## New Models
- Mistral 7B (previous issue #126 )
- Mixtral 7B x 8
- OpenLlama 3b (previous issue #127)

**Comment by casper-hansen** [comment]
Hi @kartikayk, I wonder if Mixtral (or Mixture of Experts models) is on the roadmap and if we can expect support for this new type of model?
