### ISSUE TITLE
test_lora_finetune and test_full_finetune multi-device testing

### ISSUE THREAD

**Issue by rohan-varma** [pytorch/torchtune#473]
Currently, a very preliminary and hacky version of "multi device" finetune test is enabled by just running on a single CPU w/FSDP in [test_lora_finetune](https://github.com/pytorch-labs/torchtune/blob/main/tests/recipes/test_lora_finetune.py). We should comprehensively re think our story around multi-device testing, i.e.:

1. Launch w/ `tune --nproc-per-node x` to actually simulate how a user would do so instead of using `single_box_init`
2. Figure out our story for init_process_group backend being gloo/nccl/multi-backend based on the device
3. Understand FSDP's limitations in CPU scenario (seems to be some issue around checkpointing when running on CPU / gloo
4. Ideally test on multiple GPUs instead of CPUs to more clearly simulate our desired use cases for these recipes.

**Comment by ebsmothers** [comment]
Done in #537
