### ISSUE TITLE
Configuring WandB logger broken / can't easily configure?

### ISSUE THREAD

**Issue by rohan-varma** [pytorch/torchtune#479]
When switching config from:`  _component_: torchtune.utils.metric_logging.DisLogger`

to:
`  _component_: torchtune.utils.metric_logging.WandBLogger`

I hit `TypeError: WandBLogger.__init__() missing 1 required positional argument: 'project'`. 

I see that I probably need to add `project` the nested config, but as a user this does give me a little overhead as I need to go into the logger impl, find what project is, understand it, figure out the type, and add something to my config. I could also understand if this is reasonable to expect from users, but it seems more overhead than before when I could simply pass in an override `--metric_logger=wandb` and I'd get wandB logging out of the box.

We should discuss the UX here and figure out whether @RdoubleA 's work to improve config instantiation will help.

**Comment by felipemello1** [comment]
Closing it since there are no updates since March. If it is still an issue, please reopen it! thanks :)
