### ISSUE TITLE
Create custom Llama2 models for quick experimentation

### ISSUE THREAD

**Issue by msaroufim** [pytorch/torchtune#585]
For local development working with a full llama model is a bit slow and we could instead have much smaller llama variants for iterative debugging https://huggingface.co/karpathy/tinyllamas

came from feedback from thomas https://x.com/capetorch/status/1772357944379670768?s=20

**Comment by tcapelle** [comment]
Hi, to be clear, what I want is not TinyLlama, I want a Random Llama 2 that is very small, similar to what the H4 team does for testing transformers.

This way I can prototype fast on my macbook, with a let's say 1M param model that is a full arch with random weights but really small. Let's say:
```python
from torchtune.models.llama2 import llama2
from torchtune.modules import TransformerDecoder
from torchtune.utils.checkpoint import save_checkpoint, load_checkpoint

def random_llama2_tiny(max_batch_size = None) -> TransformerDecoder:
    """
    Builder for creating a Llama2 model initialized w/ the default 7b parameter values
    from https://arxiv.org/abs/2307.09288

    Args:
        max_batch_size (Optional[int]): Maximum batch size to be passed to KVCache.

    Returns:
        TransformerDecoder: Instantiation of Llama2 7B model
    """
    return llama2(
        vocab_size=32_000,
        num_layers=2,
        num_heads=4,
        num_kv_heads=4,
        embed_dim=128,
        max_seq_len=4096,
        max_batch_size=max_batch_size,
        attn_dropout=0.0,
        norm_eps=1e-5,
    )

m = random_llama2_tiny()
chpt_dict = {"model": m}
save_checkpoint(chpt_dict, 'tiny_llama/model.pth')
```
I haven't figured out yet why there are 2 functions to save and load (also on the `_checkpointer.py` file).

**Comment by kartikayk** [comment]
@tcapelle so the conversion to and from torchtune format is something that you/users shouldn't have to worry about. We read and write HF-format checkpoints. All of this is abstracted away from the user. There's more info about how to use the checkpointer here (we dont have our live docs and tutorials "live" just yet): https://github.com/pytorch/torchtune/blob/main/recipes/README.md

For an example of how you use the checkpointer to load and save the model look at the recipe code:
load_checkpoint: https://github.com/pytorch/torchtune/blob/main/recipes/full_finetune_single_device.py#L96
save_checkpoint: https://github.com/pytorch/torchtune/blob/main/recipes/full_finetune_single_device.py#L274

And for an example of how this is setup, look here: https://github.com/pytorch/torchtune/blob/main/recipes/configs/llama2/13B_full.yaml#L43

Following is a screenshot of how I load HF checkpoints in my interpreter and run a forward on it:

![image](https://github.com/pytorch/torchtune/assets/47255723/004d66df-1c1f-4aac-bbca-1422142e473a)


I'll have more documentation around this soon. Let me know if this helps answers your questions? Or if there's a specific error you're seeing.

The ```hf_to_tune``` functions ar just state_dict convertors which replace the ```convert_weights_from_blah_to_blah``` scripts that most libraries have. Hope this makes sense!

**Comment by ebsmothers** [comment]
@tcapelle re the tiny model: we do have versions of this as testing utilities, but currently nothing importable as a part of the core library. For instance we have a utility to construct a set of CLI overrides that can be appended to a `tune` command to run the fine-tuning script on a small model. The utility is [here](https://github.com/pytorch/torchtune/blob/b5abdb3e1632d89348f11aa505749a3d0ea80d1a/tests/recipes/utils.py#L41-L52) and you can see an example usage where we append it to a fine-tuning command [here](https://github.com/pytorch/torchtune/blob/b5abdb3e1632d89348f11aa505749a3d0ea80d1a/tests/recipes/test_full_finetune_distributed.py#L71-L72). (I know this is a bit different than the example you gave, so if you want something at the model builder level instead of the script/recipe level it should look more like your code snippet.)

**Comment by tcapelle** [comment]
Amazing, will check and report back.

**Comment by kartikayk** [comment]
Actually @tcapelle here's the code for what you want to do. Let me know if this helps:

```
from torchtune.models.llama2 import llama2
from torchtune.models import convert_weights


tiny_llama = llama2(
    vocab_size=32_000,
    num_layers=2,
    num_heads=4,
    num_kv_heads=4,
    embed_dim=128,
    max_seq_len=4096
)

tune_sd = tiny_llama.state_dict()

# convert to hf format
hf_sd = convert_weights.tune_to_hf(state_dict, num_heads=4, num_kv_heads=4, dim=128)

#inspect the keys
 hf_sd.keys()
```

Here's the output:
<img width="1728" alt="image" src="https://github.com/pytorch/torchtune/assets/47255723/72d0e9f5-a25c-406f-a82a-ab2cc439d920">

**Comment by tcapelle** [comment]
got it working thanks!

I actually stopped using the functions from: `from torchtune.utils.checkpoint import save_checkpoint, load_checkpoint`
