### ISSUE TITLE
Will there be a docker?

### ISSUE THREAD

**Issue by Playerrrrr** [pytorch/torchtune#622]
Hoping/looking forward to one.

**Comment by ebsmothers** [comment]
Hi @Playerrrrr thanks for creating the issue. We are still working on our build story and hope to be making improvements on this front soon. So far we have been mainly focused on nightly pip packages as a first step, but could consider docker images as a follow-up to that. Can you give a bit more info on why you'd prefer docker to e.g. pip install here?

**Comment by tcapelle** [comment]
here you go!
```docker
FROM pytorch/pytorch:2.2.2-cuda12.1-cudnn8-runtime


WORKDIR /workspace/torchtune

# RUN git config --global --add safe.directory /workspace/torchtune # add this if you have issues

COPY . /workspace/torchtune

RUN python -m pip install -e ".[optional-dependencies]"

ENTRYPOINT ["/bin/bash"]
```

Then you need to build this:

```bash
docker build . -t torchtune:v0
```
and my handy docker command to run stuff:
```bash
docker run \
  --privileged \
  --gpus '"all"' \
  --shm-size=10g \
  --rm \
  -it \
  --name=torchtune \
  --ipc=host \
  --ulimit memlock=-1 \
  --ulimit stack=67108864 \
  -e $WANDB_API_KEY \
  torchtune:v0
```

**Comment by ebsmothers** [comment]
Closing this, thanks for addressing it @tcapelle!

**Comment by austinmw** [comment]
Would be helpful when orchestrating training to have a prebuilt public docker image available to point to (to prevent needing to build your own, push it, authenticate to it, etc.)
