### ISSUE TITLE
DPO + attribution

### ISSUE THREAD

**Issue by lvwerra** [pytorch/torchtune#782]
Hi there, congrats on the release of `torchtune`! I noticed that the `DPOLoss` class is a copy of `trl`'s implementation. While copying the code is totally fine it would be nice to add some attribution to the original implementation. 

`torchtune` code:
https://github.com/pytorch/torchtune/blob/main/torchtune/modules/loss/dpo.py#L14

`trl` code:
https://github.com/huggingface/trl/blob/5d1deb1445828cfd0e947cb3a7925b1c03a283fc/trl/trainer/dpo_trainer.py#L844

**Comment by kartikayk** [comment]
@lvwerra thanks so much for flagging. To provide more context, this particular PR was a contribution to the code base by the community and we completely missed this. Apologies! We'll fix this ASAP, add an attribution both on the README and in the docstring and be more cognizant moving forward. Growing pains for a new library - we're still figuring some of these things out. Thanks again for flagging! We really appreciate the awesome work you all do and are hoping there are many more interop opportunities in the future! Thanks again.

**Comment by lvwerra** [comment]
Totally ok, these things happen especially if you ship fast 🚀  Thanks for fixing it so quickly!

**Comment by RdoubleA** [comment]
Should be updated now with #784, let us know if there's any other concerns
