### ISSUE TITLE
llama 3 consolidated.00.pth doesnt exist

### ISSUE THREAD

**Issue by bdytx5** [pytorch/torchtune#804]
how do i create this from the safetensors dowloaded from the tune download command?

**Comment by RdoubleA** [comment]
Hey @bdytx5, if you've followed the [tutorial](https://pytorch.org/torchtune/stable/tutorials/llama3.html) and downloaded with a similar tune command to `tune download meta-llama/Meta-Llama-3-8B --output-dir <checkpoint_dir> --hf-token <ACCESS TOKEN>`, then you should see the `consolidated.00.pth` file in the `original` folder in your checkpoint dir:
```
(torchtune) [rafiayub@devgpu004.ash8 /data/users/rafiayub/torchtune (main)]$ ls /tmp/Llama-3-8B-hf/original
consolidated.00.pth  params.json  tokenizer.model
```

**Comment by bdytx5** [comment]
ah ok now I see it. Thanks!
