### ISSUE TITLE
ImportError: cannot import name 'return_and_correct_aliasing' on Kaggle notebook

### ISSUE THREAD

**Issue by shure-dev** [pytorch/torchtune#806]
Kaggle notebook

After installing this package, then I run `! tune --help`

`ImportError: cannot import name 'return_and_correct_aliasing' from 'torch.utils._python_dispatch' (/opt/conda/lib/python3.10/site-packages/torch/utils/_python_dispatch.py)`

**Comment by badarrrr** [comment]
I met the same error after installing torchtune

**Comment by felipemello1** [comment]
@shure-dev , I believe its the same error as reported here: https://github.com/pytorch/torchtune/issues/1259

Can you please update your pytorch to >2.3.0?

`pip install --upgrade torch==2.4.0`

**Comment by RdoubleA** [comment]
Resolved in #1259
