### ISSUE TITLE
vRAM usage display for 70B models

### ISSUE THREAD

**Issue by BedirT** [pytorch/torchtune#839]
I love how detailed the 7-8B models are displayed with their expected VRAM usage on the readme + docs. I would love to see 70B as well, I think it would help a lot for people looking for what options they have in terms of compute. 

This is one of the main reasons axolotl doing very well, I think torchtune would benefit from the same approach.

**Comment by kartikayk** [comment]
@BedirT love this feedback! Thanks so much for taking the time to write this out - it means a lot to us.

For 70B, we have a couple of enhancements/improvements in the works which should hopefully make these slightly more accessible. As soon as these land, we'll publish these numbers :) Let me know if there are some issues you're facing and we'd love to take a look as well. Thanks once again for the awesome feedback.

**Comment by rohan-varma** [comment]
@BedirT Thanks for this feedback! Currently we have the 70B models enabled for both Llama2 and Llama 3 with LoRA + FSDP distributed training. We'll publish memory and efficiency numbers soon, but a few things off the top of my mind that we're looking into are:

1. QLoRA + distributed training for the 70B model. Currently, there are some gaps in composing QLoRA + FSDP together, but @weifengpy, @awgu and others have been looking into this.
2. Investigating CPU offloading for 70B use cases. CPU offloading with FSDP has generally been known to be quite slow and have some gaps, but recent changes including upstream of faster CPU kernels for Adam into PyTorch could help here (this would require a nightly build of pytorch). 
3. Composability of low precision optimizers wih FSDP. Some techniques such as bitsandbytes' 8-bit adam optimizers don't work out of the box with FSDP and there are several gaps to plug here. Plus folks like @lessw2020, @janeyx99 @msaroufim have all been thinking about low precision optimizers in general.

**Comment by BedirT** [comment]
Thanks for the answers @rohan-varma @kartikayk !

Excited to see the numbers 🙏. I think it would also be very nice to see some comparisons with other libraries. Not just in terms of compute requirements but also ease of use and how it is actually is by pytorch itself. Love the base level updates u guys do from the source! https://github.com/pytorch/torchtune/commit/bec7babec9c924a0ee7ad27e3f6582bc5bd1fef5

@kartikayk mainly I wanted to know what the requirement would look like in terms of GPUs so that I could direct my efforts towards the right instance. I am currently trying with `ml.p4d` and if it couldn't handle I will switch to `ml.p4de`. Im interested in the LoRA setup rather than QLoRA.

Thanks!

**Comment by felipemello1** [comment]
Closing it since it was added to the readme. Please feel free to reopen if there questions still! :)
