### ISSUE TITLE
LLama 3 : can't load the hugging face state dict

### ISSUE THREAD

**Issue by Optimox** [pytorch/torchtune#860]
Hello,

I am trying to get familiar with the qlora single device recipe with LLama3.

I have been able to download the weights from hugging face without any problem.

I am then running the following simple setup code (similar to the qlora single device recipe):

```
from torchtune.modules.peft.peft_utils import (
    get_adapter_params,
    get_merged_lora_ckpt,
    set_trainable_params,
    validate_missing_and_unexpected_for_lora,
)
from torchtune.models.convert_weights import hf_to_tune, meta_to_tune
from torchtune.models.llama3 import qlora_llama3_8b, lora_llama3_8b
from torchtune.utils import FullModelMetaCheckpointer, FullModelHFCheckpointer


import torch
from torchtune import config, modules, utils
MY_DTYPE = torch.bfloat16


_device = utils.get_device(device="cuda")
with utils.set_default_dtype(MY_DTYPE), _device :
    lora_model = lora_llama3_8b(lora_attn_modules=['q_proj', 'v_proj', 'k_proj', 'output_proj'], quantize_base=True).to(MY_DTYPE)

adapter_params = get_adapter_params(lora_model)
set_trainable_params(lora_model, adapter_params)

checkpointer = FullModelHFCheckpointer("./meta-llama/Meta-Llama-3-8B/",
                                       checkpoint_files=["./meta-llama/Meta-Llama-3-8B/pytorch_model-00001-of-00002.bin",
                                                         "./meta-llama/Meta-Llama-3-8B/pytorch_model-00002-of-00002.bin",
                                                        ],
                                       model_type="llama3",
                                      output_dir="../../logs/")

base_model_state_dict = checkpointer.load_checkpoint() 

base_missing, base_unexpected = lora_model.load_state_dict(
            base_model_state_dict["model"], strict=False
        )
```

I can't load the base model state dict into the the lora model because there seem to be shape mismatches:

```
RuntimeError: Error(s) in loading state_dict for TransformerDecoder:
	size mismatch for tok_embeddings.weight: copying a param with shape torch.Size([32000, 4096]) from checkpoint, the shape in current model is torch.Size([128256, 4096]).
	size mismatch for layers.0.attn.k_proj.weight: copying a param with shape torch.Size([4096, 4096]) from checkpoint, the shape in current model is torch.Size([1024, 4096]).
	size mismatch for layers.0.attn.v_proj.weight: copying a param with shape torch.Size([4096, 4096]) from checkpoint, the shape in current model is torch.Size([1024, 4096]).
	size mismatch for layers.0.mlp.w1.weight: copying a param with shape torch.Size([11008, 4096]) from checkpoint, the shape in current model is torch.Size([14336, 4096]).
```

Could you tell me what I did wrong ?
Thank you very much for your help

**Comment by kartikayk** [comment]
Thanks for opening this issue!

Hmm, this seems like you're maybe loading the wrong checkpoint files? I don't see any ```.bin``` files in the [repo](https://huggingface.co/meta-llama/Meta-Llama-3-8B/tree/main)? I only see ```safetensors``` files which is also in the Meta format. [Here's](https://github.com/pytorch/torchtune/blob/main/recipes/configs/llama3/8B_qlora_single_device.yaml#L32) how this works with the ```consolidated.00.pth``` file. You should be able to replace this with the safetensor files without changing the checkpointer. Just make sure you point to the right path.

Another hint for you're loading the wrong checkpoint is the shape of the tensor. Llama3 has a vocab of 128256, but your checkpoint has 32000 which maps to llama2 :) Hope this helps!

**Comment by Optimox** [comment]
Thanks, sorry for the dumb question, it seems that I mixed up llama2 and llama3 with a wrong copy paste...
`tune download meta-llama/Llama-2-7b-hf --output-dir meta-llama/Meta-Llama-3-8B`
