### ISSUE TITLE
Can't seem to get latest version via pip

### ISSUE THREAD

**Issue by man-shar** [pytorch/torchtune#870]
Hi,

I'm trying to install the latest (`0.1.1` as of today) which adds support for passing `chat_format=None` for llama3 models. 

`pip install --upgrade torchtune`

But I can't seem to get the latest source for the package. I still get the old stuff where `chat_format` was required.

I'm either doing something very stupid, or maybe the registry hasn't been updated or the build wheel might have an older build?

Any help appreciated!

Cheers,
Manas

**Comment by RdoubleA** [comment]
Hi @man-shar, good question. `pip install` will only get our latest stable version, which does not include the chat format changes yet. You'll need to build from source:
```
git clone https://github.com/pytorch/torchtune.git
cd torchtune
pip install .
```

**Comment by man-shar** [comment]
Ahhh, got it. THANK YOU! Will close this issue now.

Btw, this is a truly awesome library. The modularization + native pytorch is very very helpful.
