### ISSUE TITLE
Test directory structure for models doesn't match corresponding implementation files

### ISSUE THREAD

**Issue by ebsmothers** [pytorch/torchtune#905]
Right now we have e.g. `tests/torchtune/models/test_llama3.py` and `tests/torchtune/models/test_lora_llama2.py` test files for our models. This is not in line with our implementation files, which have directories `torchtune/models/llama2`, `torchtune/models/mistral`, etc. We should refactor the `tests/torchtune/models` directory to better line up with the directory structure of `torchtune/models` to improve discoverability of our test files.

**Comment by RdoubleA** [comment]
Already done
