### ISSUE TITLE
Request support for Eleuther generative task

### ISSUE THREAD

**Issue by ScottHoang** [pytorch/torchtune#921]
Hi all, 
Thank you for the excellent work you guys have been doing thus far. 
I request that we add support to Eleuther's generative tasks. 
We are not encoding batch prompts correctly, leading to an index lookup error in tok_embeddings.
Can you help?
Thank you!

**Comment by kartikayk** [comment]
Thanks so much for opening this issue. Coincidently @joecummings is working on this right now.

**Comment by joecummings** [comment]
@ScottHoang  This was enabled in #975 - check it out!

**Comment by ebsmothers** [comment]
@joecummings this should be completed, right? Gonna close the issue but re-open if I'm mistaken here
