### ISSUE TITLE
Phi-3-mini-4k-instruct missing layer key in dict

### ISSUE THREAD

**Issue by kunal-mansukhani** [pytorch/torchtune#924]
I'm trying to fine-tune Phi-3 4k mini. Using the mini_full_low_memory config. Getting `Exception: Error converting the state dict. Found unexpected key: "model.layers.0.mlp.gate_up_proj.weight". Please make sure you're loading a checkpoint with the right format. `

**Comment by kartikayk** [comment]
Thanks for opening this issue! Can you share the command you're using?

**Comment by kartikayk** [comment]
Hmm, I just ran this and it seems to work. Do you mind checking if you downloaded the right weights? This error implies that your model checkpoint doesnt have the ```gate_up_proj.weight``` which is suspicious.

**Comment by kunal-mansukhani** [comment]
I'm running  `!tune download microsoft/Phi-3-mini-4k-instruct --output-dir /tmp/Phi-3-mini-4k-instruct --hf-token <HF_TOKEN> --ignore-patterns ""` to download the model. I thought the error suggests that key "model.layers.0.mlp.gate_up_proj.weight" is present in the checkpoint I'm using, but it doesn't align with the expected keys based on the mini_full_low_memory configuration I'm using.

**Comment by kunal-mansukhani** [comment]
Solved. Wasn't using the updated version of torchtune
