### ISSUE TITLE
add llama-70B memory and perf numbers to the README table

### ISSUE THREAD

**Issue by soumith** [pytorch/torchtune#925]
only 7B numbers are there right now. Add 70B

**Comment by kartikayk** [comment]
Yup, makes sense!

cc: @ebsmothers and @joecummings - I'll roll this in with the README updates I have underway.

**Comment by kartikayk** [comment]
Update on this - I was trying to clean the table up over the weekend to capture lowest memory utilization AND peak tokens/sec for each model. Capturing the "best" for each column makes more sense that what we have currently. Unfortunately runpod was pretty flaky and I wasn't able to get these numbers. I'll focus on getting all of the numbers early this week, including the 70B numbers (tokens/sec looks pretty good compared to the numbers I saw on some of the MLX screenshots).

**Comment by kartikayk** [comment]
Took a while, but we got there in the end. This is addressed in #955. I'll add Llama3 numbers as a follow up since there is some ongoing work to improve memory footprint. We're also on the verge of landing sample packing which should improve tokens/sec by ~3x.
