### ISSUE TITLE
Can't Load the Merged Lora Weight  meta_model_2.pt.

### ISSUE THREAD

**Issue by gulizhoutao** [pytorch/torchtune#935]
I use lora to fine-tune llama3, after that I use meta_model_2.pt for generation,  however, I get the error as follows:
Traceback (most recent call last):
  File "/data1/zhoutao/anaconda3/envs/llama3/bin/tune", line 8, in <module>
    sys.exit(main())
  File "/data1/zhoutao/anaconda3/envs/llama3/lib/python3.10/site-packages/torchtune/_cli/tune.py", line 49, in main
    parser.run(args)
  File "/data1/zhoutao/anaconda3/envs/llama3/lib/python3.10/site-packages/torchtune/_cli/tune.py", line 43, in run
    args.func(args)
  File "/data1/zhoutao/anaconda3/envs/llama3/lib/python3.10/site-packages/torchtune/_cli/run.py", line 179, in _run_cmd
    self._run_single_device(args)
  File "/data1/zhoutao/anaconda3/envs/llama3/lib/python3.10/site-packages/torchtune/_cli/run.py", line 93, in _run_single_device
    runpy.run_path(str(args.recipe), run_name="__main__")
  File "/data1/zhoutao/anaconda3/envs/llama3/lib/python3.10/runpy.py", line 289, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/data1/zhoutao/anaconda3/envs/llama3/lib/python3.10/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/data1/zhoutao/anaconda3/envs/llama3/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/data1/zhoutao/anaconda3/envs/llama3/lib/python3.10/site-packages/recipes/generate.py", line 152, in <module>
    sys.exit(main())
  File "/data1/zhoutao/anaconda3/envs/llama3/lib/python3.10/site-packages/torchtune/config/_parse.py", line 50, in wrapper
    sys.exit(recipe_main(conf))
  File "/data1/zhoutao/anaconda3/envs/llama3/lib/python3.10/site-packages/recipes/generate.py", line 147, in main
    recipe.setup(cfg=cfg)
  File "/data1/zhoutao/anaconda3/envs/llama3/lib/python3.10/site-packages/recipes/generate.py", line 54, in setup
    self._model = self._setup_model(
  File "/data1/zhoutao/anaconda3/envs/llama3/lib/python3.10/site-packages/recipes/generate.py", line 72, in _setup_model
    model.load_state_dict(model_state_dict)
  File "/data1/zhoutao/anaconda3/envs/llama3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2153, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for TransformerDecoder:
	Missing key(s) in state_dict: "layers.0.attn.q_proj.lora_a.weight", "layers.0.attn.q_proj.lora_b.weight", "layers.0.attn.v_proj.lora_a.weight", "layers.0.attn.v_proj.lora_b.weight", "layers.1.attn.q_proj.lora_a.weight", "layers.1.attn.q_proj.lora_b.weight", "layers.1.attn.v_proj.lora_a.weight", "layers.1.attn.v_proj.lora_b.weight", "layers.2.attn.q_proj.lora_a.weight", "layers.2.attn.q_proj.lora_b.weight", "layers.2.attn.v_proj.lora_a.weight", "layers.2.attn.v_proj.lora_b.weight", "layers.3.attn.q_proj.lora_a.weight", "layers.3.attn.q_proj.lora_b.weight", "layers.3.attn.v_proj.lora_a.weight", "layers.3.attn.v_proj.lora_b.weight", "layers.4.attn.q_proj.lora_a.weight", "layers.4.attn.q_proj.lora_b.weight", "layers.4.attn.v_proj.lora_a.weight", "layers.4.attn.v_proj.lora_b.weight", "layers.5.attn.q_proj.lora_a.weight", "layers.5.attn.q_proj.lora_b.weight", "layers.5.attn.v_proj.lora_a.weight", "layers.5.attn.v_proj.lora_b.weight", "layers.6.attn.q_proj.lora_a.weight", "layers.6.attn.q_proj.lora_b.weight", "layers.6.attn.v_proj.lora_a.weight", "layers.6.attn.v_proj.lora_b.weight", "layers.7.attn.q_proj.lora_a.weight", "layers.7.attn.q_proj.lora_b.weight", "layers.7.attn.v_proj.lora_a.weight", "layers.7.attn.v_proj.lora_b.weight", "layers.8.attn.q_proj.lora_a.weight", "layers.8.attn.q_proj.lora_b.weight", "layers.8.attn.v_proj.lora_a.weight", "layers.8.attn.v_proj.lora_b.weight", "layers.9.attn.q_proj.lora_a.weight", "layers.9.attn.q_proj.lora_b.weight", "layers.9.attn.v_proj.lora_a.weight", "layers.9.attn.v_proj.lora_b.weight", "layers.10.attn.q_proj.lora_a.weight", "layers.10.attn.q_proj.lora_b.weight", "layers.10.attn.v_proj.lora_a.weight", "layers.10.attn.v_proj.lora_b.weight", "layers.11.attn.q_proj.lora_a.weight", "layers.11.attn.q_proj.lora_b.weight", "layers.11.attn.v_proj.lora_a.weight", "layers.11.attn.v_proj.lora_b.weight", "layers.12.attn.q_proj.lora_a.weight", "layers.12.attn.q_proj.lora_b.weight", "layers.12.attn.v_proj.lora_a.weight", "layers.12.attn.v_proj.lora_b.weight", "layers.13.attn.q_proj.lora_a.weight", "layers.13.attn.q_proj.lora_b.weight", "layers.13.attn.v_proj.lora_a.weight", "layers.13.attn.v_proj.lora_b.weight", "layers.14.attn.q_proj.lora_a.weight", "layers.14.attn.q_proj.lora_b.weight", "layers.14.attn.v_proj.lora_a.weight", "layers.14.attn.v_proj.lora_b.weight", "layers.15.attn.q_proj.lora_a.weight", "layers.15.attn.q_proj.lora_b.weight", "layers.15.attn.v_proj.lora_a.weight", "layers.15.attn.v_proj.lora_b.weight", "layers.16.attn.q_proj.lora_a.weight", "layers.16.attn.q_proj.lora_b.weight", "layers.16.attn.v_proj.lora_a.weight", "layers.16.attn.v_proj.lora_b.weight", "layers.17.attn.q_proj.lora_a.weight", "layers.17.attn.q_proj.lora_b.weight", "layers.17.attn.v_proj.lora_a.weight", "layers.17.attn.v_proj.lora_b.weight", "layers.18.attn.q_proj.lora_a.weight", "layers.18.attn.q_proj.lora_b.weight", "layers.18.attn.v_proj.lora_a.weight", "layers.18.attn.v_proj.lora_b.weight", "layers.19.attn.q_proj.lora_a.weight", "layers.19.attn.q_proj.lora_b.weight", "layers.19.attn.v_proj.lora_a.weight", "layers.19.attn.v_proj.lora_b.weight", "layers.20.attn.q_proj.lora_a.weight", "layers.20.attn.q_proj.lora_b.weight", "layers.20.attn.v_proj.lora_a.weight", "layers.20.attn.v_proj.lora_b.weight", "layers.21.attn.q_proj.lora_a.weight", "layers.21.attn.q_proj.lora_b.weight", "layers.21.attn.v_proj.lora_a.weight", "layers.21.attn.v_proj.lora_b.weight", "layers.22.attn.q_proj.lora_a.weight", "layers.22.attn.q_proj.lora_b.weight", "layers.22.attn.v_proj.lora_a.weight", "layers.22.attn.v_proj.lora_b.weight", "layers.23.attn.q_proj.lora_a.weight", "layers.23.attn.q_proj.lora_b.weight", "layers.23.attn.v_proj.lora_a.weight", "layers.23.attn.v_proj.lora_b.weight", "layers.24.attn.q_proj.lora_a.weight", "layers.24.attn.q_proj.lora_b.weight", "layers.24.attn.v_proj.lora_a.weight", "layers.24.attn.v_proj.lora_b.weight", "layers.25.attn.q_proj.lora_a.weight", "layers.25.attn.q_proj.lora_b.weight", "layers.25.attn.v_proj.lora_a.weight", "layers.25.attn.v_proj.lora_b.weight", "layers.26.attn.q_proj.lora_a.weight", "layers.26.attn.q_proj.lora_b.weight", "layers.26.attn.v_proj.lora_a.weight", "layers.26.attn.v_proj.lora_b.weight", "layers.27.attn.q_proj.lora_a.weight", "layers.27.attn.q_proj.lora_b.weight", "layers.27.attn.v_proj.lora_a.weight", "layers.27.attn.v_proj.lora_b.weight", "layers.28.attn.q_proj.lora_a.weight", "layers.28.attn.q_proj.lora_b.weight", "layers.28.attn.v_proj.lora_a.weight", "layers.28.attn.v_proj.lora_b.weight", "layers.29.attn.q_proj.lora_a.weight", "layers.29.attn.q_proj.lora_b.weight", "layers.29.attn.v_proj.lora_a.weight", "layers.29.attn.v_proj.lora_b.weight", "layers.30.attn.q_proj.lora_a.weight", "layers.30.attn.q_proj.lora_b.weight", "layers.30.attn.v_proj.lora_a.weight", "layers.30.attn.v_proj.lora_b.weight", "layers.31.attn.q_proj.lora_a.weight", "layers.31.attn.q_proj.lora_b.weight", "layers.31.attn.v_proj.lora_a.weight", "layers.31.attn.v_proj.lora_b.weight". 
How can I solve this?

**Comment by ebsmothers** [comment]
Hi @gulizhoutao, thanks for creating the issue. Are you by any chance using the model class `torchtune.models.llama3.lora_llama3_8b` in your generation config? If so, can you change to `torchtune.models.llama3.llama3_8b` instead? When torchtune saves checkpoints from your fine-tune, it merges the LoRA weights back into the original model's weights. This means that you should load the checkpoint into a regular Llama3 class, not the LoRA Llama3 one. Please let me know if this helps resolve the error you're seeing.

**Comment by gulizhoutao** [comment]
> Hi @gulizhoutao, thanks for creating the issue. Are you by any chance using the model class `torchtune.models.llama3.lora_llama3_8b` in your generation config? If so, can you change to `torchtune.models.llama3.llama3_8b` instead? When torchtune saves checkpoints from your fine-tune, it merges the LoRA weights back into the original model's weights. This means that you should load the checkpoint into a regular Llama3 class, not the LoRA Llama3 one. Please let me know if this helps resolve the error you're seeing.

Thanks for answering my question, this really worked and solve the problem.
