### ISSUE TITLE
Inferencing on GPTFAst

### ISSUE THREAD

**Issue by bjohn22** [pytorch/torchtune#938]
I m following the inferencing pipeline for gpt fast and it s not working out: the e2e workflow said: `cd gpt-fast/

python scripts/convert_hf_checkpoint.py \
--checkpoint_dir <new_dir>/Llama-2-7B-hf/ \
--model 7B
`
Here are steps to do the same. Using torchtune.utils.FullModelMetaCheckpointer worked out in tune run generate. I downloaded my weights from Meta's github not HF.
 
`python scripts/convert_hf_checkpoint.py --checkpoint_dir ./gpt-fast/torchtune_johno/Llama-3-8B --model 8B
`
![image](https://github.com/pytorch/torchtune/assets/64164805/d1c43e1f-6925-4401-aa27-861563db65ea)

Here is the error I got with the GPTFast script:
![image](https://github.com/pytorch/torchtune/assets/64164805/5cd8806c-0240-42bf-bed8-2a53eee3e204)

**Comment by kartikayk** [comment]
Thanks for opening this issue!

Looking at the [conversion script](https://github.com/pytorch-labs/gpt-fast/blob/main/scripts/convert_hf_checkpoint.py#L42) in gpt-fast, it assumes a few things:
- The checkpoint has the name ```consolidated.00.pth```
- model name param is ```Llama-3``` 

You'll need to rename the checkpoint and update the model param to make this work (I dont think ```8B``` will work looking at the code). My suggestion would be to look at the conversion script and make sure your directory structure and checkpoint name satisfy the assumptions made by gpt fast. Hope this helps!

**Comment by bjohn22** [comment]
Thank you. I modified the paths in GPT-FAST's script and generated outputs.
