### ISSUE TITLE
Missing Source Code When Installed Through Pip

### ISSUE THREAD

**Issue by DhruvSrikanth** [pytorch/torchtune#940]
## Problem

Source code missing when `torchtune` is installed using `pip`. Specifically the following block of code is missing from this [file](https://github.com/pytorch/torchtune/blob/main/torchtune/data/_types.py) - 

```python
    @classmethod
    def from_dict(cls, d: dict) -> "Message":
        """
        Construct a Message from a dictionary.

        Args:
            d (dict): dictionary containing the fields of the Message.

        Returns:
            Message: constructed Message.
        """
        return cls(
            role=d["role"],
            content=d["content"],
            masked=d.get("masked", False),
            ipython=d.get("ipython", False),
            eot=d.get("eot", True),
        )
```

#### System Specifications

- System - Apple M1 Mac Pro
- OS - MacOS Sonoma 14.4.1

#### Environment Specifications

- Python Version - 3.10.9
- Virtual Environment Used - venv
- PyTorch Version - 2.3.0
- Torchtune Version - 0.1.1

#### Steps

Run the following commands:

```bash
python -m venv .venv
source .venv/bin/activate
pip install torchtune
```

Then run the following code. This is from the `torchtune` tutorial on ***[Fine-tuning Llama3 with Chat Data](https://pytorch.org/torchtune/main/tutorials/chat.html)***:

```python
from torchtune.data import Llama2ChatFormat, Message

if __name__ == '__main__':
    sample = [
        {
            "role": "system",
            "content": "You are a helpful, respectful, and honest assistant.",
        },
        {
            "role": "user",
            "content": "Who are the most influential hip-hop artists of all time?",
        },
        {
            "role": "assistant",
            "content": "Here is a list of some of the most influential hip-hop "
            "artists of all time: 2Pac, Rakim, N.W.A., Run-D.M.C., and Nas.",
        },
    ]

    messages = [Message.from_dict(msg) for msg in sample]
    formatted_messages = Llama2ChatFormat.format(messages)
    print(formatted_messages)
```

This results in the following error:

```bash
AttributeError: type object 'Message' has no attribute 'from_dict'
```

for the line - 

```python
messages = [Message.from_dict(msg) for msg in sample]
```

**Comment by ebsmothers** [comment]
Hi @DhruvSrikanth thanks for opening the issue. I believe the `from_dict` method was added after the 0.1.1 release. Can you try to instead install the nightly release? You can use the command

```
pip install --pre torchtune --extra-index-url https://download.pytorch.org/whl/nightly/cpu --no-cache-dir
```

Then you should be able to use the `from_dict` method as expected.

**Comment by DhruvSrikanth** [comment]
Hi @ebsmothers, thanks for the quick response. Installing the nightly version works! Thanks!!
