### ISSUE TITLE
[rank1]: KeyError: 'num_key_value_heads'

### ISSUE THREAD

**Issue by mj2688** [pytorch/torchtune#946]
I am using the llama2/7B_lora template provided by torchtune to fine-tune the llama2 7B model, and below is my customized yaml content. However, I encountered a 'KeyError: num_key_value_heads' error. I checked the original yaml template and it also does not include this parameter.

my log:
(mj) ubuntu@ubuntu-7002-r8424-g12:~/mj$ tune run --nnodes 1 --nproc_per_node 2 lora_finetune_distributed --config ./custom_config.yaml
Running with torchrun...
W0507 15:51:14.198941 130538999482176 torch/distributed/run.py:757] 
W0507 15:51:14.198941 130538999482176 torch/distributed/run.py:757] *****************************************
W0507 15:51:14.198941 130538999482176 torch/distributed/run.py:757] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
W0507 15:51:14.198941 130538999482176 torch/distributed/run.py:757] *****************************************
INFO:torchtune.utils.logging:Running LoRAFinetuneRecipeDistributed with resolved config:

batch_size: 2
checkpointer:
  _component_: torchtune.utils.FullModelHFCheckpointer
  adapter_checkpoint: null
  checkpoint_dir: /home/ubuntu/smyin/open_llama_7b_V2
  checkpoint_files:
  - pytorch_model-00001-of-00002.bin
  - pytorch_model-00002-of-00002.bin
  model_type: LLAMA2
  output_dir: /tmp/Llama-2-7b-hf
  recipe_checkpoint: null
dataset:
  _component_: torchtune.datasets.alpaca_cleaned_dataset
  train_on_input: true
device: cuda
dtype: bf16
enable_activation_checkpointing: false
epochs: 1
gradient_accumulation_steps: 32
log_every_n_steps: 1
log_peak_memory_stats: false
loss:
  _component_: torch.nn.CrossEntropyLoss
lr_scheduler:
  _component_: torchtune.modules.get_cosine_schedule_with_warmup
  num_warmup_steps: 100
max_steps_per_epoch: null
metric_logger:
  _component_: torchtune.utils.metric_logging.DiskLogger
  log_dir: /home/ubuntu/mj/alog
model:
  _component_: torchtune.models.llama2.lora_llama2_7b
  apply_lora_to_mlp: false
  apply_lora_to_output: false
  lora_alpha: 16
  lora_attn_modules:
  - q_proj
  - v_proj
  lora_rank: 8
optimizer:
  _component_: torch.optim.AdamW
  lr: 0.0003
  weight_decay: 0.01
output_dir: /home/ubuntu/mj/alog
resume_from_checkpoint: false
seed: null
shuffle: true
tokenizer:
  _component_: torchtune.models.llama2.llama2_tokenizer
  path: /home/ubuntu/smyin/open_llama_7b_V2/tokenizer.model

DEBUG:torchtune.utils.logging:Setting manual seed to local seed 649868757. Local seed is seed + rank = 649868757 + 0
DEBUG:torchtune.utils.logging:Setting manual seed to local seed 649868758. Local seed is seed + rank = 649868757 + 1
Writing logs to /home/ubuntu/mj/alog/log_1715068277.txt
[rank0]: Traceback (most recent call last):
[rank0]:   File "/home/ubuntu/.conda/envs/mj/lib/python3.8/site-packages/recipes/lora_finetune_distributed.py", line 615, in <module>
[rank0]:     sys.exit(recipe_main())
[rank0]:   File "/home/ubuntu/.conda/envs/mj/lib/python3.8/site-packages/torchtune/config/_parse.py", line 50, in wrapper
[rank0]:     sys.exit(recipe_main(conf))
[rank0]:   File "/home/ubuntu/.conda/envs/mj/lib/python3.8/site-packages/recipes/lora_finetune_distributed.py", line 609, in recipe_main
[rank0]:     recipe.setup(cfg=cfg)
[rank0]:   File "/home/ubuntu/.conda/envs/mj/lib/python3.8/site-packages/recipes/lora_finetune_distributed.py", line 203, in setup
[rank0]:     checkpoint_dict = self.load_checkpoint(cfg_checkpointer=cfg.checkpointer)
[rank0]:   File "/home/ubuntu/.conda/envs/mj/lib/python3.8/site-packages/recipes/lora_finetune_distributed.py", line 148, in load_checkpoint
[rank0]:     checkpoint_dict = self._checkpointer.load_checkpoint()
[rank0]:   File "/home/ubuntu/.conda/envs/mj/lib/python3.8/site-packages/torchtune/utils/_checkpointing/_checkpointer.py", line 387, in load_checkpoint
[rank0]:     num_kv_heads=self._config["num_key_value_heads"],
[rank0]: KeyError: 'num_key_value_heads'
[rank1]: Traceback (most recent call last):
[rank1]:   File "/home/ubuntu/.conda/envs/mj/lib/python3.8/site-packages/recipes/lora_finetune_distributed.py", line 615, in <module>
[rank1]:     sys.exit(recipe_main())
[rank1]:   File "/home/ubuntu/.conda/envs/mj/lib/python3.8/site-packages/torchtune/config/_parse.py", line 50, in wrapper
[rank1]:     sys.exit(recipe_main(conf))
[rank1]:   File "/home/ubuntu/.conda/envs/mj/lib/python3.8/site-packages/recipes/lora_finetune_distributed.py", line 609, in recipe_main
[rank1]:     recipe.setup(cfg=cfg)
[rank1]:   File "/home/ubuntu/.conda/envs/mj/lib/python3.8/site-packages/recipes/lora_finetune_distributed.py", line 203, in setup
[rank1]:     checkpoint_dict = self.load_checkpoint(cfg_checkpointer=cfg.checkpointer)
[rank1]:   File "/home/ubuntu/.conda/envs/mj/lib/python3.8/site-packages/recipes/lora_finetune_distributed.py", line 148, in load_checkpoint
[rank1]:     checkpoint_dict = self._checkpointer.load_checkpoint()
[rank1]:   File "/home/ubuntu/.conda/envs/mj/lib/python3.8/site-packages/torchtune/utils/_checkpointing/_checkpointer.py", line 387, in load_checkpoint
[rank1]:     num_kv_heads=self._config["num_key_value_heads"],
[rank1]: KeyError: 'num_key_value_heads'
E0507 15:51:19.237765 130538999482176 torch/distributed/elastic/multiprocessing/api.py:826] failed (exitcode: 1) local_rank: 0 (pid: 2754906) of binary: /home/ubuntu/.conda/envs/mj/bin/python
Traceback (most recent call last):
  File "/home/ubuntu/.conda/envs/mj/bin/tune", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/.conda/envs/mj/lib/python3.8/site-packages/torchtune/_cli/tune.py", line 49, in main
    parser.run(args)
  File "/home/ubuntu/.conda/envs/mj/lib/python3.8/site-packages/torchtune/_cli/tune.py", line 43, in run
    args.func(args)
  File "/home/ubuntu/.conda/envs/mj/lib/python3.8/site-packages/torchtune/_cli/run.py", line 177, in _run_cmd
    self._run_distributed(args)
  File "/home/ubuntu/.conda/envs/mj/lib/python3.8/site-packages/torchtune/_cli/run.py", line 88, in _run_distributed
    run(args)
  File "/home/ubuntu/.conda/envs/mj/lib/python3.8/site-packages/torch/distributed/run.py", line 870, in run
    elastic_launch(
  File "/home/ubuntu/.conda/envs/mj/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/ubuntu/.conda/envs/mj/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 263, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
/home/ubuntu/.conda/envs/mj/lib/python3.8/site-packages/recipes/lora_finetune_distributed.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-05-07_15:51:19
  host      : ubuntu-7002-r8424-g12.local
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 2754907)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-05-07_15:51:19
  host      : ubuntu-7002-r8424-g12.local
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 2754906)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

my yaml:
# Config for multi-device LoRA finetuning in lora_finetune_distributed.py
# using a Llama2 7B model
#
# This config assumes that you've run the following command before launching
# this run:
#   tune download meta-llama/Llama-2-7b-hf --output-dir /tmp/Llama-2-7b-hf --hf-token <HF_TOKEN>
#
# To launch on 2 devices, run the following command from root:
#   tune run --nnodes 1 --nproc_per_node 2 lora_finetune_distributed --config llama2/7B_lora
#
# You can add specific overrides through the command line. For example
# to override the checkpointer directory while launching training
# you can run:
#   tune run --nnodes 1 --nproc_per_node 2 lora_finetune_distributed --config llama2/7B_lora checkpointer.checkpoint_dir=<YOUR_CHECKPOINT_DIR>
#
# This config works best when the model is being fine-tuned on 2+ GPUs.
# For single device LoRA finetuning please use 7B_lora_single_device.yaml
# or 7B_qlora_single_device.yaml

# Model Arguments
model:
  _component_: torchtune.models.llama2.lora_llama2_7b
  lora_attn_modules: ['q_proj', 'v_proj']
  apply_lora_to_mlp: False
  apply_lora_to_output: False
  lora_rank: 8
  lora_alpha: 16

tokenizer:
  _component_: torchtune.models.llama2.llama2_tokenizer
  path: /home/ubuntu/smyin/open_llama_7b_V2/tokenizer.model

checkpointer:
  _component_: torchtune.utils.FullModelHFCheckpointer
  checkpoint_dir: /home/ubuntu/smyin/open_llama_7b_V2
  checkpoint_files: [
    pytorch_model-00001-of-00002.bin,
    pytorch_model-00002-of-00002.bin
  ]
  adapter_checkpoint: null
  recipe_checkpoint: null
  output_dir: /tmp/Llama-2-7b-hf
  model_type: LLAMA2
resume_from_checkpoint: False

# Dataset and Sampler
dataset:
  _component_: torchtune.datasets.alpaca_cleaned_dataset
  train_on_input: True
seed: null
shuffle: True
batch_size: 2

# Optimizer and Scheduler
optimizer:
  _component_: torch.optim.AdamW
  weight_decay: 0.01
  lr: 3e-4
lr_scheduler:
  _component_: torchtune.modules.get_cosine_schedule_with_warmup
  num_warmup_steps: 100

loss:
  _component_: torch.nn.CrossEntropyLoss

# Training
epochs: 1
max_steps_per_epoch: null
gradient_accumulation_steps: 32

# Logging
output_dir: /home/ubuntu/mj/alog
metric_logger:
  _component_: torchtune.utils.metric_logging.DiskLogger
  log_dir: ${output_dir}
log_every_n_steps: 1
log_peak_memory_stats: False

# Environment
device: cuda
dtype: bf16
enable_activation_checkpointing: False
/
/

```[tasklist]
### Tasks
- [ ] Add a draft title or issue reference here
```

**Comment by rohan-varma** [comment]
So IIUC, that particular config that's being looked up for `num_key_value_heads` is not the actual training config, but the HF config associated with the checkpoint, and it appears to be missing that particular key. It does look like in general we do assume that key is there: https://github.com/pytorch/torchtune/blob/main/torchtune/utils/_checkpointing/_checkpointer.py#L402.

cc @kartikayk for more context.

**Comment by kartikayk** [comment]
Thanks for filing this issue! 

Unfortunately, the repo (https://huggingface.co/openlm-research/open_llama_7b_v2/tree/main) seems to have a config which is missing the ```num_key_value_heads``` (we depend on this config file to give us information needed to correctly convert checkpoints). If you modify the config.json file and add ```"num_key_value_heads": 32``` to it, things should work. I tested this locally. Let me know if you run into issues.

**Comment by kartikayk** [comment]
@mj2688 I'll close this issue for now since it seems to address the failure. But please feel free to reopen if we should be following up on this.
