### ISSUE TITLE
Having issues on Running Llama-3-70B

### ISSUE THREAD

**Issue by BedirT** [pytorch/torchtune#962]
Hi,

I am trying to run fine-tuning Llama-3-70B-Instruct on Sagemaker Notebook with `p4de.24xlarge` instance. I am not sure whats wrong, but it seems like package cannot see `torchtune.models.llama3.lora_llama3_70b` module.

The command I am running is:
```
tune run --nproc_per_node 8 lora_finetune_distributed --config Llama-3-70B-lora.yaml
```

I installed the torchtune using pip and here are my torch versions:
```
torch==2.2.2
torchao==0.1
torchaudio==2.2.2
torchtune==0.1.1
torchvision==0.17.2
```

Since Sagemaker environments are handled by Conda, I am also using a Conda environment in my setup. The error I get:
```
AttributeError: module 'torchtune.models.llama3' has no attribute 'lora_llama3_70b'. Did you mean: 'lora_llama3_8b'?
```

**Comment by kartikayk** [comment]
Unfortunately this feature is not in our stable package release. Can you i[nstall the nightly build](https://pytorch.org/torchtune/main/install.html) and see if it fixes the issue?

**Comment by JadarTheObscurity** [comment]
It works for me with the following torch version
```
torch                    2.3.1+cu121
torchao                  0.1
torchaudio               2.3.1+cu121
torchtune                0.2.0.dev20240623+cu121
torchvision              0.18.1+cu121
```

**Comment by ebsmothers** [comment]
@BedirT were you able to figure this out? I am gonna close this issue as I think @kartikayk's suggestion should resolve it for you. If not, please feel free to reopen.
