### ISSUE TITLE
Issues with Llama-3-8b Context Window

### ISSUE THREAD

**Issue by 1Krypt0** [pytorch/torchtune#967]
I am trying to fine-tune a Llama-3-8B-Instruct model with qlora on a dataset whose entries are near the 8k context limit, but never above it. I have already applied the same dataset using Mistral and had no problem with it.

However, when I am trying to use Llama, I get the following error:

``ValueError: seq_len (7762) of input tensor should be smaller than max_seq_len (4096)``

What should I change in the config for the max_seq_len to be set at 8192 instead of 4096?

**Comment by RdoubleA** [comment]
Hi @1Krypt0, what is your config that you are using?

Typically to set the `max_seq_len` you can modify the dataset parameter in the config like so:
```
dataset:
  _component_: torchtune.datasets.alpaca_dataset
  max_seq_len: 8192
```
Or you can override in the CLI:
```
tune run --nproc_per_node 4 full_finetune_distributed --config llama3/8B_full dataset.max_seq_len=8192
```

**Comment by 1Krypt0** [comment]
Hey! After investigating further I believe the problem was due to my version of torchtune simply being outdated. In my source code, llama 3 was set to have a ``max_seq_len`` of 4096. I have since changed it and it is now functioning properly.
