### ISSUE TITLE
Using a simple model for torchtune setup testing in PRs?

### ISSUE THREAD

**Issue by mikekgfb** [pytorch/torchtune#978]
I'm trying to run torchtune as an on-pr test for torchchat to ensure on-going comptaibility.  Alas, llama3 can't be used because on-pr tests can't use HF tokens.  Can you please suggest an alternative setup, or enable stories15M from Andrej's tinyllamas collection as a standin?

https://github.com/pytorch/torchchat/actions/runs/9071903213/job/24926494708
```
  + tune download stories15M --output-dir ./Meta-Llama-3-8B
  Ignoring files matching the following patterns: *.safetensors
  usage: tune download <repo-id> [OPTIONS]
  tune download: error: Repository 'stories15M' not found on the Hugging Face Hub.
  ```
  
  cc: @byjlw

**Comment by ebsmothers** [comment]
Hi @mikekgfb one suggestion is to use one of the checkpoints [here](https://github.com/pytorch/torchtune/blob/f3611e505dfb3a7fd1bf81181ea250e63d854e0e/tests/cache_artifacts.sh#L16-L18) which you can just get via curl. These are more or less random weights though, so if you want to test specifically for generation quality you may want to go another route.

**Comment by RdoubleA** [comment]
Hi @mikekgfb, closing this issue as it seems the question was answered but please reopen if you have more follow-ups. Thanks!
